### ISSUE TITLE
Internal server error: Objects are not valid as a React child 

### ISSUE THREAD

**Issue by ahhshm** [BuilderIO/qwik#1152]
### Qwik Version

0.0.105

### Operating System (or Browser)

Chromium 104.0.5112.79 Arch Linux

### Node Version (if applicable)

16.16.0 (I've also tried 14.20.0 and 16.0.0)

### Which component is affected?

Qwik React

### Expected Behaviour

I just created a simple component with `qwikify$()` and expected it to work like a normal qwik component:
```tsx
export const Hello = qwikify$(() => <div>hello from react</div>);

export default component$(() => {
  return (
    <div>
      <Hello client:visible />
    </div>
  );
});
```

### Actual Behaviour

When I start the dev server with `npm run dev.ssr` I get this error:

```
9:14:29 AM [vite] Internal server error: Objects are not valid as a React child (found: object with keys {type, props, key}). If you meant to render a collection of children, use an array instead.
      at renderNodeDestructiveImpl (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6183:11)
      at renderNodeDestructive (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
      at renderIndeterminateComponent (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
      at renderElement (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
      at renderNodeDestructiveImpl (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
      at renderNodeDestructive (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
      at renderContextProvider (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5924:3)
      at renderElement (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6021:11)
      at renderNodeDestructiveImpl (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
      at renderNodeDestructive (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
      at retryTask (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6532:5)
      at performWork (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6580:7)
      at /home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6904:12
      at scheduleWork (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:78:3)
      at startWork (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6903:3)
      at renderToStringImpl (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6977:3)
      at Proxy.renderToString (/home/amir/Documents/code/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:7065:10)
      at Module.render (/node_modules/@builder.io/qwik-react/lib/server.f07a53ac.js:28:38)
      at eval (/src/qwikifyqrl_component_zh94hie0ick.js:45:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async renderRoot (/home/amir/Documents/code/qwik-app/node_modules/@builder.io/qwik/core.cjs:5396:9)
      at async renderSSR (/home/amir/Documents/code/qwik-app/node_modules/@builder.io/qwik/core.cjs:5392:9)
      at async Proxy.renderToStream (/home/amir/Documents/code/qwik-app/node_modules/@builder.io/qwik/server.cjs:588:3)
      at async file:///home/amir/Documents/code/qwik-app/node_modules/@builder.io/qwik/optimizer.mjs:1787:32
```
And when I start the dev server with `npm run dev.client` the component doesn't show up! If I render these two components side by side:
```tsx
export const Hello = qwikify$(() => <div>hello from react</div>);
export const QwikHello = component$(() => <div>hello from qwik</div>);

export default component$(() => {
    return (
      <div>
        <Hello client:visible />
        <QwikHello />
      </div>
    );
});
```
This is what I see:

![image](https://user-images.githubusercontent.com/87268103/187015788-b679a448-a90c-49ac-8c36-322f395d151f.png)

#### deps
```json
"dependencies": {
  "@builder.io/qwik-react": "^0.0.100",
  "@emotion/react": "^11.10.0",
  "@emotion/server": "^11.10.0",
  "hoist-non-react-statics": "^3.3.2",
  "react": "^18.2.0",
  "react-dom": "^18.2.0"
}
```
#### vite.config.ts
```ts
import { defineConfig } from "vite";
import { qwikVite } from "@builder.io/qwik/optimizer";
import { qwikCity } from "@builder.io/qwik-city/vite";
import { qwikReact } from "@builder.io/qwik-react";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite(), qwikReact(), tsconfigPaths()],
  };
});
```

**Comment by ahhshm** [comment]
I don't have this problem after the beta release. So I close it.

**Comment by chendong-xie** [comment]
this issue are still exist

**Comment by ahhshm** [comment]
> this issue are still exist

If you still get the error, feel free to re-open the issue. Also a reproduction repo/stackblitz would be awesome.
