### ISSUE TITLE
Dynamic require of "/inlinedQRL.js" is not supported

### ISSUE THREAD

**Issue by mahmudz** [BuilderIO/qwik#1352]
### Qwik Version

0.9.0

### Operating System (or Browser)

Windows 11 / Chrome 105.0

### Node Version (if applicable)

16.13

### Which component is affected?

Qwik Runtime

### Expected Behaviour

A successful build and preview.

### Actual Behaviour

When a CSS file is empty, throws an exception when running `npm run preview`

#### Code
```tsx
import { component$, useStylesScoped$ } from '@builder.io/qwik';
import { QwikLogo } from '../icons/qwik';
import styles from './header.css?inline';

export default component$(() => {
  useStylesScoped$(styles);
  
  return (
    <header class={'flex items-center justify-between py-4'}>
         <QwikLogo />
    </header>
    )
}
```

Exception:
```
✓ Built client modules
✓ Built preview (ssr) modules

  ➜  Local:   http://127.0.0.1:4173/
  ➜  Network: use --host to expose
file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/server.mjs:18
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "/inlinedQRL.js" is not supported
    at file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/server.mjs:18:9
    at Object.importSymbol (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/server.mjs:72:22)
    at resolve (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:5495:43)
    at AsyncFunction.resolveLazy [as $resolveLazy$] (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:5502:40)
    at _useStyles (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:7297:28)
    at useStylesScopedQrl (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:7246:5)
    at file:///D:/Workspaces/Experiments/qwik-app/server/entry.preview.mjs:44:3
    at invoke (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:179:26)
    at file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:5518:28
    at then (file:///D:/Workspaces/Experiments/qwik-app/node_modules/@builder.io/qwik/core.mjs:115:56)
```

### Additional Information

Was it normal? Or we should handle exceptions in a more meaningful way to point out the issue?

**Comment by manucorporat** [comment]
can you share your `vite.config.ts` file? please

**Comment by mahmudz** [comment]
Here it is.
```ts
import { defineConfig } from 'vite';
import { qwikVite } from '@builder.io/qwik/optimizer';
import { qwikCity } from '@builder.io/qwik-city/vite';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
  };
});
```

**Comment by manucorporat** [comment]
Thanks a lot! fixing here! https://github.com/BuilderIO/qwik/pull/1356
