### ISSUE TITLE
Routing to a component with `onPost` is causing server dependencies to be loaded into the client

### ISSUE THREAD

**Issue by meenie** [BuilderIO/qwik#1477]
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

18

### Which component is affected?

Qwik City

### Expected Behaviour

When using the `<Link />` component to route to another component that has `onPost` (or any other `on___` methods) defined, the libraries imported and utilized within `onPost` _should not_ be imported into the client.

### Actual Behaviour

When using the `<Link />` component to route to another component that has `onPost` (or any other `on___` methods) defined, the libraries imported and utilized within `onPost` _are_ imported into the browser. If those libraries are node only, then it will break the application. It also bloats the memory of the browser having to load extra libraries that aren't even needed.

On a side note, when you directly load the route in the browser URL bar, then the libraries are _not_ imported. This only happens when you use `<Link />` to route to this component.

### Additional Information

You can reproduce the issue here: https://stackblitz.com/edit/qwik-starter-nmrofc?file=src%2Froutes%2Fflower%2Ffoo.ts,src%2Froutes%2Fflower%2Findex.tsx

When clicking on the button to route to the Flower, notice the console message that shows up in the browser. This should not happen.  If you load the `/flower` page directly, this message does not appear in the browser console.

**Comment by cmbartschat** [comment]
Adding on here, even just a function defined within the same file as the `onGet` like so:

```
export const makeData = () => {
  // Logic here
};

export const onGet: RequestHandler<Data> = async () => {
  return makeData();
};
```

I'm seeing that the `makeData` function is being loaded on the client after following a `<Link>`. 

I'm even seeing this with the Express integration running `npm run build && npm run serve` which I'm pretty sure is a production build.

**Comment by meenie** [comment]
I believe the issue here is that when you load the page with the `onGet()`, the server SSRs the page and no JS is loaded.  And even if Qwik needs to load the component, it's only loading the `component$` chunk that was created, so all is still fine because it still has yet to download the `onGet()`.  But when you use the `<Link />` component to go to another route, it loads the would route file, including the `onGet()`. And because of that, the browser tries to resolve any dependencies imported into the route for the `onGet()` to work and if any of those dependencies are Node-only, it will blow up the browser.

**Comment by cayter** [comment]
Remix is currently using this [approach](https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles) after months of community feedback which I think will save lots of troubles for the core team to implement smart detection for server only modules.

**Comment by cayter** [comment]
Remix is currently using this [approach](https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles) after months of community feedback which I think will save lots of troubles for the core team to implement smart detection for server only modules.

DX is definitely not as good as now we'd need to pay extra attention to what should be in `*.server.ts`, but I think this makes it clearer and easier for Qwik to focus things that matter more.

**Comment by cayter** [comment]
Remix is currently using this [approach](https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles) after months of community usage/feedback which I think will save lots of troubles for the core team to implement smart detection for server only modules.

DX is definitely not as good as now we'd need to pay extra attention to what should be in `*.server.ts`, but I think this makes it clearer and easier for Qwik team to focus on things that matter more given how bloated NPM modules are and I don't think there's a standard official guideline for module authors to follow at the moment, although the bundlers are actually pushing for something like this:

- [webpack](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)
- [esbuild](https://esbuild.github.io/api/#conditionally-injecting-a-file)

**Comment by jwickers** [comment]
Although this Stackblitz uses an older version this happens on the current latest for both Qwik / QwickCity.

This seems to be an issue with the optimizer?

I think it is supposed to remove those and I saw some rust tests with components using `onGet` so I'm not sure why it would be in the output...

Also happens in `preview` so not just a Dev mode issue.

**Comment by wmertens** [comment]
Could it be that the transitive dependencies don't get filtered out, maybe because they aren't marked as pure @manucorporat ?

**Comment by cmbartschat** [comment]
Progress has been made! I'm still seeing this issue using `npm run dev`, but otherwise, it seems like this issue has disappeared in `npm run preview` or using the express.

It seems like https://github.com/BuilderIO/qwik/pull/2260 could have been what did it?

https://stackblitz.com/edit/qwik-server-dependencies-before?file=README.md

https://stackblitz.com/edit/qwik-server-dependencies?file=README.md

**Comment by dlford** [comment]
For me, dev works  (without the use of `Link`, still get the errors with `Link`), but now `npm run preview` breaks the API routes with the error `GT.parse is not a function`, which I assume is coming from either `prisma`, `ioredis`, or `bcrypt`.

**Comment by dlford** [comment]
Adding to this issue, even without using the `<Link  />` component, production builds are failing due to server dependencies leaking into browser bundles.

Running `npm run qwik add express`, and then `npm run build`, the build process hangs indefinitely after `✓ Built client modules`.

After running `npm run qwik add netlify-edge`, and `npm run build`, I get the following error:

```sh
✓ Built client modules

'.prisma/client/index-browser' is imported by .prisma/client/index-browser?commonjs-external, but could not be resolved – treating it as an external dependency
[commonjs--resolver] Cannot bundle Node.js built-in "crypto" imported from "node_modules/idgen/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /home/dan/git/qwik-playground/node_modules/idgen/index.js
error during build:
Error: Cannot bundle Node.js built-in "crypto" imported from "node_modules/idgen/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///home/dan/git/qwik-playground/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///home/dan/git/qwik-playground/node_modules/rollup/dist/es/shared/rollup.js:21587:12)
    at Object.error (file:///home/dan/git/qwik-playground/node_modules/rollup/dist/es/shared/rollup.js:22541:20)
    at Object.resolveId (file:///home/dan/git/qwik-playground/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33611:34)
    at Object.handler (file:///home/dan/git/qwik-playground/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45606:19)
    at file:///home/dan/git/qwik-playground/node_modules/rollup/dist/es/shared/rollup.js:22748:40
```

`npm run dev` still works as expected so long as the `<Link />` component is not used.

If it helps, here is the repo - https://codeberg.org/dlford/qwik-playground

**Comment by jwickers** [comment]
I'm seeing this issue on DEV mode too, I'm doing things client side causing the page component to be loaded, eg: `/src/routes/foo/[id]/index.tsx` is fetched, inside of the file I see a bunch of blocks related to  components  like:

```ts
export const MyComponent1 = /*#__PURE__*/
componentQrl(qrlDEV(()=>import("/src/mycomponent1_component_cnvksxbfms4.js"), "MyComponent1_component_cNvksxbFmS4", {
    file: "/Users/.../src/routes/foo/[id]/index.tsx",
    lo: 2516,
    hi: 3600,
    displayName: "MyComponent1_component"
}));
```

and a few blocks verbatim from my page source that should not be there like the `onGet`, `onStaticGenerate` and *maybe* the `head` functions.

Also that files imports `pg` which is used in `onStaticGenerate` in my case, but could as well have bee used in `onGet` as:
```ts
const pg = __vite__cjsImport2_pg.__esModule ? __vite__cjsImport2_pg.default : __vite__cjsImport2_pg;
```
