### ISSUE TITLE
Can't build project with qwik@0.10.0 when import file outside src folder

### ISSUE THREAD

**Issue by langbamit** [BuilderIO/qwik#1701]
### Qwik Version

0.10.0

### Operating System (or Browser)

Brave Browser

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

Build successfully.

### Actual Behaviour

https://stackblitz.com/edit/qwik-starter-wcrn2p?file=tsconfig.json,src%2Froutes%2Findex.tsx,counter%2Fcounter.tsx

Open new terminal, run `npm run build`

```
$ qwik build

tsc --incremental --noEmit
vite build

vite v3.1.1 building for production...
✓ 47 modules transformed.
[vite:build-import-analysis] Parse error @:8:9
file: /home/projects/qwik-starter-wcrn2p/counter/counter.tsx:10:2
 8:       <p>Count: {store.count}</p>
 9:       <p>
10:         <button onClick$={() => store.count++}>Increment</button>
      ^
11:       </p>
12:     </div>
error during build:
Error: Parse error @:8:9
    at parse$b (file:///home/projects/qwik-starter-wcrn2p/node_modules/vite/dist/node/chunks/dep-a713b95d.js:33714:355)
    at Object.transform (file:///home/projects/qwik-starter-wcrn2p/node_modules/vite/dist/node/chunks/dep-a713b95d.js:42902:27)
```

### Additional Information

Change qwik version to 0.9.0 it work again.

Updated:

Change qwik version to 0.9.0 success build but has error in runtime with `npm run preview`:
`React is not defined`

**Comment by langbamit** [comment]
Add `srcDir` option to `qwikVite` solved my issue. Sorry for my noise.
