### ISSUE TITLE
qwikPlugin.api.getManifest is not a function

### ISSUE THREAD

**Issue by kwaa** [BuilderIO/qwik#1844]
### Qwik Version

0.11.1

### Operating System (or Browser)

StackBlitz

### Node Version (if applicable)

16.14.2

### Which component is affected?

Qwik City

### Expected Behaviour

- Fork [qwik-starter](https://github.com/mhevery/qwik-starter) in StackBlitz
- `turbo add @builder.io/qwik@0.11.1`
- `turbo add @builder.io/qwik-city@0.0.117`
- `npm run dev`

The dev server should be started without errors.

### Actual Behaviour

```
[vite] Internal server error: qwikPlugin.api.getManifest is not a function
  File: /home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs
  23901|    if (r3.paramNames.length > 0) {
  23902|      const paramNames = JSON.stringify(r3.paramNames);
  23903|      return `[ ${pattern}, ${moduleLoaders}, ${paramNames} ]`;
     |              ^
  23904|    }
  23905|    return `[ ${pattern}, ${moduleLoaders} ]`;
      at getClientRouteBundleNames (/home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs:23909:63)
      at createRouteData (/home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs:23898:46)
      at createRoutes (/home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs:23887:20)
      at generateQwikCityPlan (/home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs:23942:3)
      at Context.load (/home/projects/qwik-starter-oxka85/node_modules/@builder.io/qwik-city/vite/index.cjs:28678:20)
      at Object.load (file:///home/projects/qwik-starter-oxka85/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41107:46)
      at loadAndTransform (file:///home/projects/qwik-starter-oxka85/node_modules/vite/dist/node/chunks/dep-a713b95d.js:37334:46)
      at doTransform (file:///home/projects/qwik-starter-oxka85/node_modules/vite/dist/node/chunks/dep-a713b95d.js:37320:20)
```

### Additional Information

Minimal reproduction: https://stackblitz.com/edit/qwik-starter-oxka85
This error starts at `@builder.io/qwik-city@0.0.114`.
`0.0.112` works fine, while `0.0.113` is `Failed to resolve entry for package`

**Comment by kwaa** [comment]
This issue has been fixed in `@builder.io/qwik-city@0.0.118`.
