### ISSUE TITLE
Failing to build with `build.server`

### ISSUE THREAD

**Issue by tunnckoCore** [BuilderIO/qwik#1865]
### Qwik Version

0.11.1

### Operating System (or Browser)

Linux / Firefox

### Node Version (if applicable)

18.3

### Which component is affected?

Qwik City

### Expected Behaviour

I just used the Basic example from `npm create qwik`, and added the CloudFlare Pages integration.

### Actual Behaviour

Then ran `npm run build` and it builds OK, thing is when I run `build.server` it errors with 

```
[sigma@arckos qwik-cf-kv]$ yarn build.server
yarn run v1.22.19
$ vite build --ssr src/entry.cloudflare-pages.tsx
vite v3.1.7 building SSR bundle for production...
✓ 12 modules transformed.
[commonjs--resolver] Failed to resolve entry for package "@builder.io/qwik-city". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@builder.io/qwik-city". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34841:11)
    at resolvePackageEntry (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34838:5)
    at tryNodeResolve (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34584:20)
    at Object.resolveId (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:34357:28)
    at Object.handler (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-0ebb5606.js:45996:19)
    at file:///home/sigma/github/qwik-cf-kv/node_modules/rollup/dist/es/shared/rollup.js:22710:40

```

I'm not sure if i even need to run that script, but still.

Also, kinda not related to above but same stuff which feels like "unfinished" and polishing.
Seems like the `qwik build preview` is also failing with

```
Error: Cannot bundle Node.js built-in "node:http" imported from "node_modules/node-fetch/src/index.js". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///home/sigma/github/qwik-cf-kv/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at throwPluginError (file:///home/sigma/github/qwik-cf-kv/node_modules/rollup/dist/es/shared/rollup.js:21781:12)
    at Object.error (file:///home/sigma/github/qwik-cf-kv/node_modules/rollup/dist/es/shared/rollup.js:22503:20)
    at Object.resolveId (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:34370:34)
    at Object.handler (file:///home/sigma/github/qwik-cf-kv/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:45996:19)
    at file:///home/sigma/github/qwik-cf-kv/node_modules/rollup/dist/es/shared/rollup.js:22710:40

```

**Comment by zanettin** [comment]
Hi @tunnckoCore 
Just gave it a spin with the v0.12.0 release of qwik and did the following steps:
```
pnpm create qwik@latest (selected `basic app` qwik city)
cd qwik-app
pnpm qwik add cloudflare-pages
```

`pnpm  build.server` worked as it should 👍 
`pnpm qwik build preview` works as it should 👍 

i also have the 2nd mentioned error when adding the `netlify-edge` adapter which is also mentioned here: https://github.com/BuilderIO/qwik/issues/1393, but works for me with the `cloudflare-pages` adapter.

do you want to try it on your side as well with the latest version of qwik?

**Comment by tunnckoCore** [comment]
Heya @zanettin 

yea, everything seems to work properly now.

Thanks.
