### ISSUE TITLE
Vite server proxy does not work with Qwik-city / Qwik plugins

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2004]
### Qwik Version

0.12.1

### Operating System (or Browser)

Chrome 106.0.5249.119 (Official Build) (arm64)

### Node Version (if applicable)

v18.11.0

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

To enable same-origin cookies to an existing api backend, a proxy is necessary. All suggested techniques/workarounds have been tried without success. Please see [Discord Thread](https://discord.com/channels/842438759945601056/937421500879867994/1039071149155422268) summary.

### Actual Behaviour

Proxy does not forward and same-origin is not possible.

### Additional Information

Vite server proxy works **without** plugins:
```
export default defineConfig(() => {
  return {
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:4000/api',
          changeOrigin: true,
          secure: false,
          rewrite: (path) => path.replace(/^\/api/, '')
        },
      }
    },
    build: { sourcemap: true },
    plugins: [
      // qwikCity(),
      // qwikVite(),
      // tsconfigPaths(),
      // qwikReact()
    ],
    preview: {
      headers: {
        "Cache-Control": "public, max-age=600",
      },
    },
  };
});
```

Vite server proxy does **NOT** work with plugins:
```
export default defineConfig(() => {
  return {
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:4000/api',
          changeOrigin: true,
          secure: false,
          rewrite: (path) => path.replace(/^\/api/, '')
        },
      }
    },
    build: { sourcemap: true },
    plugins: [
      qwikCity(),
      qwikVite(),
      tsconfigPaths(),
      qwikReact()
    ],
    preview: {
      headers: {
        "Cache-Control": "public, max-age=600",
      },
    },
  };
});
```

Using the above configuration with the target set to your favorite url (on the same protocol) is the fastest way to reproduce this issue. (e.g. http://fubar.tld)

**Comment by n8sabes** [comment]
See #2073 with three workarounds, and explanation of limitations w/ vite server and plugins.

**Comment by n8sabes** [comment]
There is a bug with the vite server that causes an infinite reload loop.

1. Trigger a call to the local vite server proxy
2. Reload the page, or update the source to trigger an HMR refresh

The page goes into an infinite reload loop and causes the server to generate the following error infinitely with every page reload:

```shell
[HPM] Upgrading to WebSocket
[HPM] WebSocket error: Error: write after end
    at new NodeError (node:internal/errors:393:5)
    at _write (node:internal/streams/writable:322:11)
    at Writable.write (node:internal/streams/writable:337:10)
    at Sender$1.sendFrame (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:55386:20)
    at Sender$1.close (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:55114:12)
    at WebSocket$1.close (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:56160:18)
    at Receiver$1.receiverOnConclude (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:56983:18)
    at Receiver$1.emit (node:events:513:28)
    at Receiver$1.controlMessage (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:54885:14)
    at Receiver$1.getData (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:54732:42)
    at Receiver$1.startLoop (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:54451:22)
    at Receiver$1._write (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:54386:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.socketOnData (file:///~~~/node_modules/.pnpm/vite@3.2.5_@types+node@18.11.14/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:57132:37)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
```

Also see #2073

**Comment by n8sabes** [comment]
@manucorporat, Is there any way to get a little help with this issue?

There is absolutely no workaround and I've been trying to wait on this fix, but I’m at a stand still with product Qwik development at this point.

Qwik City is overriding / breaking Vite Server routes so it's impossible to reach backend api server via proxy. Alternatively, building Qwik main locally results in hanging so now even the custom route workaround isn’t working.

Super fast to reproduce:

**SETUP**
1. `pnpm create qwik` 
2. Update `vite.config.ts` to config below:

**RUN IT**
A. Run `pnpm preview` and navigate to `localhost:4173/foo` -- works
B. Run `pnpm dev` and navigate to `localhost:5173/foo ` -- route not found
C. Run `pnpm dev` with local qwik build and navigate to `localhost:5173/foo ` -- hangs

From: [Vite Server Options](https://vitejs.dev/config/server-options.html#server-proxy)
```
// vite.config.ts

import { defineConfig } from 'vite';
import { qwikVite } from '@builder.io/qwik/optimizer';
import { qwikCity } from '@builder.io/qwik-city/vite';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig(() => {
  return {
    server: {
      proxy: {
        '/foo': {
          target: 'http://jsonplaceholder.typicode.com',
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/foo/, ''),
        },
      },
    },
    plugins: [
      qwikCity(),
      qwikVite(),
      tsconfigPaths()
    ],
    preview: {
      headers: {
        'Cache-Control': 'public, max-age=600',
      },
    },
  };
});
```

**Comment by n8sabes** [comment]
I found the issue in dev-server.ts and will work on a PR this afternoon.

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/pull/2542
