### ISSUE TITLE
Adaptor : Static build fail on windows

### ISSUE THREAD

**Issue by saifulazfar** [BuilderIO/qwik#2006]
### Qwik Version

0.12.1

### Operating System (or Browser)

win11

### Which component is affected?

Starters / CLI

### Expected Behaviour

not sure why the build fail because absolute path on windows...below are my  static vite config

```
import { staticAdaptor } from '@builder.io/qwik-city/adaptors/static/vite';
import { extendConfig } from '@builder.io/qwik-city/vite';
import baseConfig from '../../vite.config';

export default extendConfig(baseConfig, () => {
  return {
    build: {
      ssr: true,
      rollupOptions: {
        input: ['@qwik-city-plan'],
      },
    },
    plugins: [
      staticAdaptor({
        origin: 'https://yoursite.qwik.dev',
      }),
    ],
  };
});

```

### Actual Behaviour

```
✓ Built client modules

error during build:
Error [PLUGIN_ERROR]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:387:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1116:11)
    at defaultResolve (node:internal/modules/esm/resolve:1196:3)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ESMLoader.import (node:internal/modules/esm/loader:528:22)
    at importModuleDynamically (node:internal/modules/esm/translators:110:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at mainThread (file:///C:/Users/Saifu/Desktop/qwik-basic-app/node_modules/.pnpm/@builder.io+qwik-city@0.0.118/node_modules/@builder.io/qwik-city/static/node.mjs:359:43)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by findborg** [comment]
I have been having the same problem

**Comment by findborg** [comment]
I have updated.  But,  it kinda broke everything.
~~~
10:09:12 AM [vite] Internal server error: __vite_ssr_import_1__.getLocale is not a function
      at QwikCity_component_useWatch_AaAlzKH0KlQ (C:\wamp\www\frames\home\node_modules\@builder.io\qwik-city\index.qwik.mjs:296:19)
      at invoke (C:\wamp\www\frames\home\node_modules\@builder.io\qwik\core.cjs:648:30)
      at C:\wamp\www\frames\home\node_modules\@builder.io\qwik\core.cjs:6162:32
      at async Promise.all (index 0)
      at async renderRoot (C:\wamp\www\frames\home\node_modules\@builder.io\qwik\core.cjs:6644:9)
      at async renderSSR (C:\wamp\www\frames\home\node_modules\@builder.io\qwik\core.cjs:6640:9)
      at async Proxy.renderToStream (C:\wamp\www\frames\home\node_modules\@builder.io\qwik\server.cjs:605:3)
      at async C:\wamp\www\frames\home\node_modules\@builder.io\qwik\optimizer.cjs:1785:28
~~~

**Comment by shairez** [comment]
Thanks for the help @robisim74 ! 🙏
