### ISSUE TITLE
Express Adaptor not working

### ISSUE THREAD

**Issue by hoaidev** [BuilderIO/qwik#2055]
### Qwik Version

0.12.1

### Operating System (or Browser)

WSL2, Chrome

### Node Version (if applicable)

19.0.1

### Which component is affected?

Qwik City

### Expected Behaviour

After adding the express server adaptor via "yarn qwik add" and "yarn build.server" and "yarn serve" should be successful.

### Actual Behaviour

yarn run v1.22.4
$ vite build -c adaptors/express/vite.config.ts
vite v3.2.1 building SSR bundle for production...
✓ 17 modules transformed.
server/entry.express.mjs                9.37 KiB
server/@qwik-city-plan.mjs              9.52 KiB
server/entry.ssr.mjs                    2.81 KiB
server/assets/index.qwik.75699133.mjs   5.36 KiB
Missing client manifest, loading symbols in the client might 404
Missing client manifest, loading symbols in the client might 404
QWIK ERROR Code(31) [AsyncFunction: invokeQRL] {
  getSymbol: [Function: getSymbol],
  getHash: [Function: getHash],
  resolve: [AsyncFunction: resolve],
  '$resolveLazy$': [Function: resolveLazy],
  '$setContainer$': [Function: setContainer],
  '$chunk$': null,
  '$symbol$': 's_dznIGAlrcag',
  '$refSymbol$': null,
  '$hash$': 'dznIGAlrcag',
  getFn: [Function: invokeFn],
  '$capture$': null,
  '$captureRef$': [ { count: 0, number: 20 } ],
  '$dev$': null
} Error: Code(31)
    at logError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:61:54)
    at logErrorAndStop (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:67:17)
    at qError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:132:12)
    at serializeQRL (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:490:15)
    at file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:38
    at Array.map (<anonymous>)
    at serializeQRLs (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:25)
    at renderNode (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:6938:62)
    at processData (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7017:16)
    at file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7079:26

**Comment by hoaidev** [comment]
After tried upgrading "@builder.io/qwik": "0.13.0-dev20221108030156"

Missing client manifest, loading symbols in the client might 404
Missing client manifest, loading symbols in the client might 404
QWIK ERROR Code(31) s_dznIGAlrcag Error: Code(31)
    at logError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:61:54)
    at logErrorAndStop (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:67:17)
    at qError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:132:12)
    at serializeQRL (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:490:15)
    at file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:38
    at Array.map (<anonymous>)
    at serializeQRLs (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:25)
    at renderNode (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7118:62)
    at processData (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7200:16)
    at file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7262:26
QWIK ERROR Code(31) Link_component_a_onClick_hA9UPaY8sNQ Error: Code(31)
    at logError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:61:54)
    at logErrorAndStop (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:67:17)
    at qError (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:132:12)
    at serializeQRL (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:490:15)
    at file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:38
    at Array.map (<anonymous>)
    at serializeQRLs (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:519:25)
    at renderNode (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7118:62)
    at processData (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7200:16)
    at walkChildren (file:///home/hoaint/devspace/qwik-app/node_modules/@builder.io/qwik/core.mjs:7237:16)

SSG results
Generated: 2 pages
Duration: 365.9 ms
Average: 182.9 ms per page

**Comment by adamdbradley** [comment]
Were you able to run `npm run build`, so that it ensures both `build.client` and `build.server` run? The `build.client` build is required for the server build.

**Comment by manucorporat** [comment]
`qwik build` is able to parallelize. Instead i agree we could have a better error message in the build.
