### ISSUE TITLE
Netlify Adaptor generates invalid regexes for dynamic routes

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#2101]
### Qwik Version

0.13.1

### Operating System (or Browser)

Debian Linux

### Which component is affected?

Starters / CLI

### Expected Behaviour

Adding the Netlify adaptor should allow me to publish a site on Netlify's edge platform. Which it does, when there are no dynamic routes in the project.

### Actual Behaviour

During the build, I receive this build error, once per dynamic route in my project.

```bash
7:55:35 PM:     {
7:55:35 PM:       "instancePath": "/routes/0/pattern",
7:55:35 PM:       "schemaPath": "#/properties/routes/items/properties/pattern/errorMessage",
7:55:35 PM:       "keyword": "errorMessage",
7:55:35 PM:       "params": {
7:55:35 PM:         "errors": [
7:55:35 PM:           {
7:55:35 PM:             "instancePath": "/routes/0/pattern",
7:55:35 PM:             "schemaPath": "#/properties/routes/items/properties/pattern/format",
7:55:35 PM:             "keyword": "format",
7:55:35 PM:             "params": {
7:55:35 PM:               "format": "regexPattern"
7:55:36 PM: Creating deploy upload records
7:55:35 PM:             },
7:55:35 PM:             "message": "must match format \"regexPattern\"",
7:55:35 PM:             "emUsed": true
7:55:35 PM:           }
7:55:36 PM: Failed during stage 'building site': Build script returned non-zero exit code: 4 (https://ntl.fyi/exit-code-4)
7:55:35 PM:         ]
7:55:35 PM:       },
7:55:35 PM:       "message": "must match format /^\\^.*\\$$/"
7:55:35 PM:     }
```

The error trace looks like this
```bash
7:55:35 PM:   Error location
7:55:35 PM:   During Edge Functions bundling
7:55:35 PM:       at validateEdgeFunctionsManifest (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins_core/edge_functions/validate_manifest/validate_edge_functions_manifest.js:76:15)
7:55:35 PM:       at async coreStep (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/plugins_core/edge_functions/index.js:43:5)
7:55:35 PM:       at async fireCoreStep (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/steps/core_step.js:9:89)
7:55:35 PM:       at async tFireStep (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/time/main.js:16:63)
7:55:35 PM:       at async runStep (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/steps/run_step.js:27:270)
7:55:35 PM:       at async pReduce.index (file:///opt/buildhome/node-deps/node_modules/@netlify/build/lib/steps/run_steps.js:12:325)
7:55:35 PM:       at async Promise.all (index 0)
7:55:35 PM:       at async next (file:///opt/buildhome/node-deps/node_modules/p-reduce/index.js:15:44)
```

**Comment by nnelgxorz** [comment]
Seems to be cause because the route pattern strings start and end with forward slashes. If we remove those, it should validate correctly. At least according to my experimenting on Regexr.
