### ISSUE TITLE
When I want to use vite.config.ts resolve.aliases, I get QWIK WARN Duplicate implementations of "JSXNode" found

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2214]
### Qwik Version

0.13.3

### Operating System (or Browser)

Debian GNU/Linux 11 (bullseye)

### Which component is affected?

Qwik Runtime

### Expected Behaviour

I have to be able to use [Vite resolve.aliases](https://vitejs.dev/config/shared-options.html#resolve-alias) instead of [tsconfig.json paths](https://www.typescriptlang.org/tsconfig#paths)

### Actual Behaviour

I get this error:

```
container | QWIK WARN Duplicate implementations of "JSXNode" found
container | QWIK ERROR Missing <head>. Global styles could not be rendered. Please render a <head> element at the root of the app Error: Missing <head>. Global styles could not be rendered. Please render a <head> element at the root of the app
container |     at logError (/Projects/SiteQwik/node_modules/@builder.io/qwik/core.cjs:73:58)
container |     at renderRoot (/Projects/SiteQwik/node_modules/@builder.io/qwik/core.cjs:6850:17)
container |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
container |     at async renderSSR (/Projects/SiteQwik/node_modules/@builder.io/qwik/core.cjs:6838:9)
container |     at async Proxy.renderToStream (/Base/Qwik/node_modules/@builder.io/qwik/server.cjs:663:3)
container |     at async /Base/Qwik/node_modules/@builder.io/qwik/optimizer.cjs:1768:28
```

### Additional Information

I changed the `vite.config.js` from:

```
import { defineConfig, loadEnv } from 'vite'
import { qwikVite } from '@builder.io/qwik/optimizer'
import { qwikCity } from '@builder.io/qwik-city/vite'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig(() => {
  return {
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
    preview: {
      headers: {
        'Cache-Control': 'public, max-age=600',
      },
    },
    server: {
      host: '0.0.0.0',
      hmr: {
        clientPort: 443
      }
    }
  };
});
```

to:

```
import { defineConfig, loadEnv } from 'vite'
import { qwikVite } from '@builder.io/qwik/optimizer'
import { qwikCity } from '@builder.io/qwik-city/vite'
import tsconfigPaths from 'vite-tsconfig-paths'
const path = require(`path`)
const fs = require('fs')

const aliases = {
  'Base': 'src/Base/Exports',
  'Forms': 'src/Modules/Forms/Exports',
}

const resolvedAliases = Object.fromEntries(
  Object.entries(aliases).map(([key, value]) => [key, path.resolve(__dirname, value)]),
)

export default defineConfig(() => {
  return {
    resolve: {
      alias: resolvedAliases,
      preserveSymlinks: true
    },
    plugins: [qwikCity(), qwikVite(), tsconfigPaths()],
    preview: {
      headers: {
        'Cache-Control': 'public, max-age=600',
      },
    },
    server: {
      host: '0.0.0.0',
      hmr: {
        clientPort: 443
      }
    }
  };
});
```

The previous config file was working just fine. After this change, it broke and gave me the error message above.

**Comment by officialpiyush** [comment]
happened to me, out of the box after creating a new project with `pnpm create qwik@latest`, started the dev server using `pnpm dev`.
Browser renders a blank screen with no errors in browser console, but with `QWIK WARN Duplicate implementations of "JSXNode" found` error in the terminal.

![image](https://user-images.githubusercontent.com/18086566/216394400-387625b9-53a2-4a36-9f72-20316696e4ad.png)
