### ISSUE TITLE
Error building app which uses redux + redux-thunk -  [🐞]

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#2721]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I am learning Redux with React and decided to build the basic project in Qwik as well. I created my own store, actions, reducers, *and use `redux-thunk` as a middleware for `redux`,* e.g. in `store.ts`:
```
export default legacy_createStore(rootReducer, {}, composeWithDevTools(applyMiddleware(thunk)));
```

Dev works fine, but trying build (or serve from preview) it runs into an error *after* `Built client modules`:

```
...
✓ Built client modules

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
error during build:
TypeError: middleware is not a function
at ...\qwik-app\node_modules\redux\lib\redux.js:703:16
    at Array.map (<anonymous>)
    at ...\qwik-app\node_modules\redux\lib\redux.js:702:31
    at createStore (...\qwik-app\node_modules\redux\lib\redux.js:162:33)
    at .../qwik-app/server/@qwik-city-plan.mjs:2:2212
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async mainThread (.../qwik-app/node_modules/@builder.io/qwik-city/static/node.mjs:642:25)
    at async Module.generate (.../qwik-app/node_modules/@builder.io/qwik-city/static/node.mjs:1495:20)
```
Redux code in question at specified file:
```
function applyMiddleware() {
  for (var _len = arguments.length, middlewares = new Array(_len), _key = 0; _key < _len; _key++) {
    middlewares[_key] = arguments[_key];
  }

  return function (createStore) {
    return function () {
      var store = createStore.apply(void 0, arguments);

      var _dispatch = function dispatch() {
        throw new Error(process.env.NODE_ENV === "production" ? formatProdErrorMessage(15) : 'Dispatching while constructing your middleware is not allowed. ' + 'Other middleware would not be applied to this dispatch.');
      };

      var middlewareAPI = {
        getState: store.getState,
        dispatch: function dispatch() {
          return _dispatch.apply(void 0, arguments);
        }
      };
      var chain = middlewares.map(function (middleware) {
        return middleware(middlewareAPI);             // <================== middleware is not a function
      });
      _dispatch = compose.apply(void 0, chain)(store.dispatch);
      return _objectSpread__default['default'](_objectSpread__default['default']({}, store), {}, {
        dispatch: _dispatch
      });
    };
  };
}
```

Let me know if there's other info that would be helpful.

NOTE: I added a reproduction copy but I don't know if `preview` or `build` can be tested through stackblitz.
I only ran into issues when running `build` or `preview`, and I was also using `express` adapter.
Steps below to reproduce.

### Reproduction

https://stackblitz.com/edit/qwik-starter-d8vhik?file=src/routes/layout.tsx

### Steps to reproduce

```
Download and unzip the stackblitz app
npm i
npm qwik add express
(npm init @eslint/config)
npm run qwik build
node server/entry.express.js
```

Results in error:
```
        return middleware(middlewareAPI);
               ^

TypeError: middleware is not a function
    at ...\qwik-starter-d8vhik\node_modules\redux\lib\redux.js:703:16
    at Array.map (<anonymous>)
    at ...\qwik-starter-d8vhik\node_modules\redux\lib\redux.js:702:31
    at createStore (...\qwik-starter-d8vhik\node_modules\redux\lib\redux.js:162:33)
    at .../qwik-starter-d8vhik/server/@qwik-city-plan.mjs:2:2014
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.53 GB / 15.85 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: ^0.16.2 => 0.16.2
    @builder.io/qwik-city: ^0.1.0-beta9 => 0.1.0-beta9
    undici: ^5.16.0 => 5.16.0
    vite: ^4.0.4 => 4.0.4
```

### Additional Information

Let me know if there's anything else I can try or if I can provide more info!

**Comment by shairez** [comment]
Thanks for reporting @jmmon 

Qwik has `useStore` which is reactive, the best way I believe to use redux is to leverage Qwik's hooks and not directly assign values inside of the component functions because then it'll opt out of the fine grained reactivity model of Qwik. 

Please feel free to re-open this issue if it's still a problem
thanks!
