### ISSUE TITLE
[🐞] Internal server error: multipart/form-data not supported when using <Form>

### ISSUE THREAD

**Issue by Ling-yunchi** [BuilderIO/qwik#3035]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When I write an action to submit a form like the example given on the official website, here is my code
```ts
import { component$ } from "@builder.io/qwik";
import { action$, Form, z, zod$ } from "@builder.io/qwik-city";

export const useSubmit = action$(
  (form) => {
    console.log(form);
  },
  zod$({
    name: z.string(),
    email: z.string().email(),
  })
);

export default component$(() => {
  const action = useSubmit();
  return (
    <div>
      <Form action={action}>
        <label>
          Name
          <input type="text" name="name" />
        </label>
        <label>
          Email
          <input type="text" name="email" />
        </label>
        <button type="submit">Submit</button>
      </Form>
    </div>
  );
});
```
I get the following error
```
22:51:51 [vite] Internal server error: multipart/form-data not supported
      at Request.formData (node:internal/deps/undici/undici:2311:19)
      at E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:23622:40
      at Object.next (E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:23864:22)
      at renderQData (E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:23730:23)
      at Object.next (E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:23864:22)
      at runNext (E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:24062:21)
      at runQwikCity (E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:24057:17)
      at E:\webstorm-workplace\qwik-form-bug\node_modules\@builder.io\qwik-city\vite\index.cjs:24437:45
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-zoredk?file=src/routes/form/index.tsx

### Steps to reproduce

Run `npm create qwik@latest` to create a  Basic App (QwikCity)
Here is the version in package.json
```json
"devDependencies": {
  "@builder.io/qwik": "0.18.1",
  "@builder.io/qwik-city": "0.2.1",
  "@types/eslint": "8.21.0",
  "@types/node": "^18.13.0",
  "@types/node-fetch": "latest",
  "@typescript-eslint/eslint-plugin": "5.51.0",
  "@typescript-eslint/parser": "5.51.0",
  "eslint": "8.33.0",
  "eslint-plugin-qwik": "0.18.1",
  "node-fetch": "3.3.0",
  "prettier": "2.8.4",
  "typescript": "4.9.5",
  "undici": "5.18.0",
  "vite": "4.1.1",
  "vite-tsconfig-paths": "3.5.0"
}
```
Then create a form submission like the example given on the website in the path `route/form/index.tsx`.
Click the submit button and an error will be reported.
`[vite] Internal server error: multipart/form-data not supported`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600U with Radeon Graphics
    Memory: 5.70 GB / 15.37 GB
  Binaries:
    Node: 18.8.0 - D:\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\yarn.CMD
    npm: 8.18.0 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.49)    
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @builder.io/qwik: 0.18.1 => 0.18.1
    @builder.io/qwik-city: 0.2.1 => 0.2.1
    undici: 5.18.0 => 5.18.0
    vite: 4.1.1 => 4.1.1
```

**Comment by manucorporat** [comment]
So weird! Gonna look into it tomorrow

**Comment by shairez** [comment]
just verified that this happens on newly generated qwik projects as well (when you go to the new "todo" page and try to submit)

**Comment by manucorporat** [comment]
How? i cant reproduce it, which version of node?

**Comment by kokecar11** [comment]
I get the error with node version **18.7.0**, with **16.13.0** I don't get the error. but I haven't tested other lts v18 versions.

**Comment by manucorporat** [comment]
Been checking `fetch()` is broken from Node 18.0.0 to Node 18.11.0, I am gonna update the required node range, so clarify this and give a better clue to developers of why it's not working!

**Comment by nikhilPatilGit** [comment]
Updating my node version to v20.4.0 fixed this issue

**Comment by JuerGenie** [comment]
so, is it `Node`'s wrong? I got this error on `bun` too 😂...

**Comment by joshdchang** [comment]
I'm getting the following error:
<img width="889" alt="image" src="https://github.com/BuilderIO/qwik/assets/17419116/4840914b-360c-4b3c-b4a6-28d5b220765a">

I'm going to file a separate issue because I think they are unrelated.
