### ISSUE TITLE
[🐞] On Windows, "exports" in package.json throws [plugin:vite:import-analysis] Missing layout component in Qwik 0.19

### ISSUE THREAD

**Issue by robisim74** [BuilderIO/qwik#3106]
### Which component is affected?

Qwik Runtime

### Describe the bug

Since Qwik version 0.19, if I have "exports" in package.json in a library project:

```
"exports": {
    ".": {
      "import": "./lib/index.qwik.mjs",
      "require": "./lib/index.qwik.cjs"
    }
  }
```

on Windows, in dev mode, I get the following error:

```
[vite] Internal server error: Missing "./src/layout_component_vklnxphuh5s.js" specifier in "my-qwik-basic-starter" package
  Plugin: vite:import-analysis
  File: C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/src/routes/layout.tsx
      at e (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14845:25)
      at n (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14845:627)
      at o (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:14845:1276)
      at resolveExports (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22033:20)
      at resolveDeepImport (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:22052:31)
      at tryNodeResolve (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21737:20)
      at Context.resolveId (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:21488:28)
      at Object.resolveId (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41612:46)
      at async TransformContext.resolve (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41363:23)
      at async normalizeUrl (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39698:34)
      at async Promise.all (index 0)
      at async TransformContext.transform (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39992:22)
      at async Object.transform (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///C:/Users/simon/Documents/Code/qwik-starter-c1pvrc/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-c1pvrc?file=package.json

### Steps to reproduce

The repro is a simple starter app with the addition of "exports". It works on Stackblitz, so you need to download it on a Windows machine, and run` npm start`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 7.30 GB / 15.92 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 110.0.5481.104
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.50)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^0.19.0 => 0.19.0 
    @builder.io/qwik-city: ^0.3.0 => 0.3.0
    undici: ^5.20.0 => 5.20.0
    vite: ^4.1.2 => 4.1.4
```

### Additional Information

The error does not occur in prod mode.

Thanks

**Comment by robisim74** [comment]
A similar issue was opened in Vite: https://github.com/vitejs/vite/issues/11035

As can be seen from it, the bug is not in Vite, and must be fixed in the framework (should be the usual path normalization problem in Windows).

The bug is annoying, because it doesn't allow Windows users to have a library and an example app in the same project.

@manucorporat I have no idea where Qwik interferes with the `exports `section of the `package.json`: it must have been a commit of version 0.19. If you can point me in the right direction, I can try to fix it, having a windows machine at hand.

Thanks!

**Comment by unworthyEnzyme** [comment]
I'm facing the same issue and what i noticed is if i start the app with `npx vite` instead of `pnpm dev` which passes `--mode ssr` flag to `vite` then there is no issue.

**Comment by gioboa** [comment]
Hi @robisim74, thanks for sharing details, with the latest version of Qwik is it still a valid issue?

**Comment by gioboa** [comment]
Thanks @robisim74 💪
