### ISSUE TITLE
[🐞] Unwanted console logs when running unit test

### ISSUE THREAD

**Issue by ahnpnl** [BuilderIO/qwik#3109]
### Which component is affected?

Qwik Runtime

### Describe the bug

I observed this error in console when running unit test on a newly generated Qwik project
```
TypeError: Cannot read properties of undefined (reading 'length')
    at memoizedBinarySearch (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:9993:25)
    at traceSegmentInternal (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:10100:17)
    at originalPositionFor$1 (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:10086:23)
    at formatError (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:41453:54)
    at TransformContext.warn (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:41381:25)
    at /Users/anh.pham/qwik-app/node_modules/@builder.io/qwik/optimizer.cjs:936:19
    at Array.forEach (<anonymous>)
    at Object.lint (/Users/anh.pham/qwik-app/node_modules/@builder.io/qwik/optimizer.cjs:933:18)
    at async Object.transform (/Users/anh.pham/qwik-app/node_modules/@builder.io/qwik/optimizer.cjs:1312:59)
    at async Object.transform (file:///Users/anh.pham/qwik-app/node_modules/vite/dist/node/chunks/dep-9912c491.js:41662:30)
```

These logs started appearing since **v0.18.0**

### Reproduction

https://github.com/ahnpnl/my-qwik-app

### Steps to reproduce

- Check out the reproduction
- Install deps with `npm` 
- Run `npm run test` and observe the logs in console

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 68.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 107.0
    Safari: 16.3
```

**Comment by ahnpnl** [comment]
a friendly ping for @manucorporat :)

**Comment by robisim74** [comment]
I did a little investigation: the error come from here:

https://github.com/BuilderIO/qwik/blob/15e00670435506e2cd7df65e94083621ec389280/packages/qwik/src/optimizer/src/plugins/eslint-plugin.ts#L49-L52

But if you debug `message`, you can see the real error (hidden by the Qwik catching):

```
{
  ruleId: null,
  fatal: true,
  severity: 2,
  message: 'Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src\\home_component_dygb4b0cyca.js` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json\n' +
    'However, that TSConfig does not include this file. Either:\n' +
    "- Change ESLint's list of included files to not include this file\n" +
    '- Change that TSConfig to include this file\n' +
    '- Create a new TSConfig that includes this file and include it in your parserOptions.project\n' +
    'See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file',
  line: undefined,
}
```
So _eslint_ is trying to lint js files generated by Qwik.

To solve it, I chose the shortest way: adding them to `.eslintignore`:

```
*.spec.tsx
*.spec.ts
*.js
```

_I think this is just a workaround, and Qwik linter should avoid linting generated files._

**Comment by ahnpnl** [comment]
Another observation is, the log is only printed out when a test file contains at least a test case which uses `userEvent` from `createDOM`

**Comment by spdiswal** [comment]
@ahnpnl I've also seen the log being printed out just by calling the `render` function from `createDOM`, e.g.:
```ts
import { createDOM } from "@builder.io/qwik/testing"

const { render } = await createDOM()
await render(<MyComponent />)
```

**Comment by ahnpnl** [comment]
In **v0.23.0** I don't see the issue anymore. Anyone can confirm?

**Comment by robisim74** [comment]
From my side it seems solved.
