### ISSUE TITLE
[🐞] Error using server$ on cloudflare

### ISSUE THREAD

**Issue by danielbrodin** [BuilderIO/qwik#3133]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have a `server$` function that I run when doing a search
```ts
export const search = server$(async (event, word: string) => {
  try {
    const data = await searchForWord(word);
    return data;
  } catch (e) {
    return [];
  }
});
```

and it works perfectly fine locally, but when I deploy to cloudflare pages (using the cloudflare adapter) and perform a search I get an error
```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--826308-production",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "%cQWIK ERROR",
        "",
        "Error: Code(30)\n    at Du (worker.mjs:83:17)\n    at qn (worker.mjs:80:38)\n    at Qa (worker.mjs:84:23)\n    at Oe (worker.mjs:91:10)\n    at Object.importSymbol (worker.mjs:106:11)\n    at d (worker.mjs:2535:23)\n    at h (worker.mjs:2538:35)\n    at worker.mjs:2541:29\n    at g2 (worker.mjs:2554:30)\n    at ke3 (worker.mjs:9762:27)",
        "_",
        "s_PLTap5600vQ"
      ],
      "level": "error",
      "timestamp": 1677225053556
    },
    {
      "message": [
        "Error: Code(30)"
      ],
      "level": "error",
      "timestamp": 1677225053556
    }
  ],
  "eventTimestamp": 1677225053542,
  "event": {
    "request": {
      "url": "https://URL/?qfunc=PLTap5600vQ",
      "method": "POST",
      "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip",
        "accept-language": "en-GB,en-US;q=0.9,en;q=0.8,sv;q=0.7",
        "cache-control": "no-cache",
        "cf-connecting-ip": "212.116.72.252",
        "cf-ipcountry": "SE",
        "cf-ray": "79e69ce89e312d59",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "content-length": "62",
        "content-type": "application/qwik-json",
        "cookie": "REDACTED",
        "host": "URL",
        "origin": "https://URL",
        "pragma": "no-cache",
        "priority": "u=1",
        "referer": "https://URL",
        "sec-ch-ua": "\"Chromium\";v=\"110\", \"Not A(Brand\";v=\"24\", \"Google Chrome\";v=\"110\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-origin",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
        "x-forwarded-proto": "https",
        "x-qrl": "PLTap5600vQ",
        "x-real-ip": "212.116.72.252"
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 0
}
```

### Reproduction

Have no production url

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 646.98 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.1.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: ^0.19.1 => 0.19.1 
    @builder.io/qwik-city: ^0.4.0 => 0.4.0 
    undici: ^5.20.0 => 5.20.0 
    vite: ^4.1.4 => 4.1.4
```

**Comment by manucorporat** [comment]
Should be fixed in the last release!

**Comment by Maikpwwq** [comment]
I am facing same issue. I made a fecth POST request to `https://nexasoft.dev/customer-record/` into a `server$(async function(data){  await fetch(...)})`, it all runs correctly in my local enviroment, catchin my folder in `routes/customer-record/index.ts`, and running my endpoint `export const onPost: RequestHandler = async (requestEvent) => { ...}`. Then I deploy my project in Vercel. During build stage everything works fine. But when in production I try to fetch my request, I get this Error: 
```
XHRPOST
https://www.nexasoft.dev/?qfunc=Jouz36DzMf4
[HTTP/2 404 Not Found 951ms]
```
Why it is calling that route that doesn't exist in my project. ie `/?qfunc=...`.
