### ISSUE TITLE
[🐞] Creating new app in current directory doesn't work without leaving and entering the directory

### ISSUE THREAD

**Issue by smucode** [BuilderIO/qwik#3184]
### Which component is affected?

Starters / CLI

### Describe the bug

I created a directory `qwik-test` and cd into it. Then ran `npm create qwik@latest` and chose the replace option, followed by `npm run qwik add`. This latter command fails with: 

```
➜  qwik-test npm run qwik add   
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^
Error: ENOENT: no such file or directory, uv_cwd
```

As a separate bug, at the time of choosing the option 
```
Directory "./" already exists. What would you like to do?
│  Overwrite and replace this directory
```
the directory is overwritten. 

I'd expect this being an option I set, and at some time later i'd confirm the whole process.

### Reproduction

http://example.com

### Steps to reproduce

```
mkdir qwik-test
cd qwik-test
npm create qwik@latest
```

Then. choose the options: 

```
┌  Let's create a  Qwik App  ✨ (v0.19.2)
│
◇  Where would you like to create your new project?
│  .
│
◇  Directory "./" already exists. What would you like to do?
│  Overwrite and replace this directory
```

Then observe the error if you run a command like  `npm run qwik add`

```
➜  qwik-test npm run qwik add   
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/depd/index.js:25:24)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/xxx/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/agentkeepalive/lib/agent.js:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1165:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1
    Memory: 8.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 110.0.5481.177
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.19.2 => 0.19.2 
    @builder.io/qwik-city: 0.4.0 => 0.4.0 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4 
```
```


### Additional Information

_No response_

**Comment by zanettin** [comment]
Hi @smucode 👋 
Thanks for mentioning this issue 🙏 I've prepared a fix for this.
The goal of the CLI is to create the directory for you in a single go. So you don't have to create anything in advance. We'll now show an info to avoid crashes as mentioned above. Thank you once again for reporting this and happy coding 😃
