### ISSUE TITLE
[🐞] CloudFlare Pages - TypeError ERR_INVALID_STATE WritableStream is locked

### ISSUE THREAD

**Issue by derkoe** [BuilderIO/qwik#3269]
### Which component is affected?

Qwik City (routing)

### Describe the bug

When running a Qwik app with CloudFlare Pages adapter locally with `wrangler` the following error is show on each request:

```
GET / 200 OK (9.81ms)
TypeError [ERR_INVALID_STATE]: Invalid state: WritableStream is locked
    at TypeError.get (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:292489)
    at getStackString (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:103714)
    at https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:99368
    at https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:101165
    at formatValue (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:103551)
    at inspect (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:92244)
    at formatWithOptionsInternal (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:115080)
    at formatWithOptions (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:116335)
    at console.value (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:1056416)
    at console.warn (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:6:1056510)
    at consoleCall (https://qwikstarterh6qgw5-elhb.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:15:389734)
    at eval (/home/projects/qwik-starter-h6qgw5/server/entry.cloudflare-pages.js:15:13290) {
  code: 'ERR_INVALID_STATE'
}
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-h6qgw5

### Steps to reproduce

- Create a new Qwik app `npm create qwik@latest`
- Add CloudFlatre Pages `npx qwik add`
- Build and launch the app with `wrangler`: `npm run build && npm run deploy`
- Open the app under http://localhost:8788/ and see the error in the log

### System Info

```shell
success Install finished in 2.352s


  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: 0.20.1 => 0.20.1 
    @builder.io/qwik-city: 0.5.2 => 0.5.2 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

### Additional Information

The application itself seems to work without issue.

**Comment by tanftw** [comment]
I still get this error even with a blank project.

**Comment by derkoe** [comment]
> (error) TypeError: This WritableStream is currently locked to a writer.

@gioboa nope never did - the app had no issue so I did not dig further

**Comment by mpeg** [comment]
I experienced this issue too, and have found the reason; the polyfill for cf pages `TextEncoderStream` doesn't properly lock the stream (among other issues) – I initially looked to fix the polyfill but then I realised that CF pages implemented the native API over a year ago 😅 so I'm sending my favorite kind of PR: one that only removes code at #5352
