### ISSUE TITLE
[🐞] RangeError: Invalid array length

### ISSUE THREAD

**Issue by sreeisalso** [BuilderIO/qwik#3336]
### Which component is affected?

Qwik City (routing)

### Describe the bug

I'm using qwik city and when I visit to particular rout it is crashing with the below message

```bash 
/home/sreeisalso/workspace/ubuntu2004/dailyzone/node_modules/.pnpm/@builder.io+qwik@0.21.0_undici@5.20.0/node_modules/@builder.io/qwik/optimizer.cjs:1668
              parts.length -= 2;
                           ^

RangeError: Invalid array length
    at findLocation (/home/sreeisalso/workspace/ubuntu2004/dailyzone/node_modules/.pnpm/@builder.io+qwik@0.21.0_undici@5.20.0/node_modules/@builder.io/qwik/optimizer.cjs:1668:28)
    at formatError (/home/sreeisalso/workspace/ubuntu2004/dailyzone/node_modules/.pnpm/@builder.io+qwik@0.21.0_undici@5.20.0/node_modules/@builder.io/qwik/optimizer.cjs:1637:21)
    at /home/sreeisalso/workspace/ubuntu2004/dailyzone/node_modules/.pnpm/@builder.io+qwik@0.21.0_undici@5.20.0/node_modules/@builder.io/qwik/optimizer.cjs:1865:17

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 3.47 GB / 7.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
  npmPackages:
    @builder.io/qwik: 0.21.0 => 0.21.0 
    @builder.io/qwik-city: 0.5.3 => 0.5.3 
    undici: 5.20.0 => 5.20.0 
    vite: 4.1.4 => 4.1.4
```

### Additional Information

Ps: Will update with the reproduction url soon

**Comment by moxival** [comment]
I believe this is the bug  https://github.com/BuilderIO/qwik/issues/3317

**Comment by sreeisalso** [comment]
> I believe this is the same bug #3317

Nope, it's not related

**Comment by moxival** [comment]
Are you sure, the error was the exact same one on the exact same place
