### ISSUE TITLE
[🐞] "Error: Code(6): Set property" when setting `class` attribute to inline `useComputed$` and using a non-serializable expression

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#3640]
### Which component is affected?

Qwik Runtime

### Describe the bug

I am setting the `class` attribute to an inline `useComputed$` and conditionally rendering elements based on a signal value. I expect this to work but am receiving an `Error: Code(6): Set property`.

```
Error: Code(6): Set property
    at createError (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:120:17)
    at logError (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:114:54)
    at _setProperty (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:1717:9)
    at executeDOMRender (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:1807:24)
    at executeContextWithSlots (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:5938:5)
    at renderMarked (https://qwikstartermtmdz9-koin--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=cfa53d04:6224:9) {node: VirtualElementImpl, key: 'className', value: 'bar'}key: "className"node: VirtualElementImpl {open: comment, close: comment, _qc_: {…}, nodeType: 111, localName: ':virtual', …}value: "bar"[[Prototype]]: Object TypeError: Cannot add property className, object is not extensible
    at _setProperty (operations.js:43:18)
    at executeDOMRender (operations.js:155:24)
    at executeContextWithSlots (visitor.js:835:5)
    at renderMarked (notify-render.js:158:9)
```

From what I can tell, Qwik is trying to update the `className` property of a `comment` rather than the actual element the inline signal is assigned to. If I extract the inline signal into a scope variable, this works fine. If I don't have a non-serializable expression, this also works fine.

### Reproduction

https://stackblitz.com/edit/qwik-starter-mtmdz9?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

```
<button
  class={useComputed$(() => (toggleSignal.value ? 'foo' : 'bar'))}
  onClick$={() => (toggleSignal.value = !toggleSignal.value)}
>
  Inline class signal with non-serializable expression
  {String(toggleSignal.value)}
  (click this twice)
</button>
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.02 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox Developer Edition: 112.0
    Safari: 16.3
  npmPackages:
    @builder.io/qwik: 0.100.0 => 0.100.0 
    @builder.io/qwik-city: ~0.100.0 => 0.100.0 
    undici: 5.21.0 => 5.21.0 
    vite: 4.2.1 => 4.2.1
```

**Comment by manucorporat** [comment]
Use methods can only be called within the root of a component, like this:
```tsx
export const BrokenButton1 = component$(() => {
  const toggleSignal = useSignal(false);
  const className = useComputed$(() => (toggleSignal.value ? 'foo' : 'bar'));
  return (
    <>
      <button
        class={className}
        onClick$={() => (toggleSignal.value = !toggleSignal.value)}
      >
        Inline class signal with conditional elements
        {toggleSignal.value ? <b>Toggle Off</b> : <i>Toggle On</i>}
        (click this twice)
      </button>
    </>
  );
});
```

But there is not much benefit of using useComputed$() for such a simple task.
