### ISSUE TITLE
[🐞] Error: R] Missing "./adaptors/express/vite" specifier in "@builder.io/qwik-city" package [plugin externalize-deps]

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#3656]
### Which component is affected?

Qwik City (routing)

### Describe the bug

A website that was being built with previous versions is not built anymore when upgraded to Qwik 0.100.0.

This is the complete log:

```
> build
> qwik build


      ............
    .::: :--------:.
   .::::  .:-------:.
  .:::::.   .:-------.
  ::::::.     .:------.
 ::::::.        :-----:
 ::::::.       .:-----.
  :::::::.     .-----.
   ::::::::..   ---:.
    .:::::::::. :-:.
     ..::::::::::::
             ...::::
     


npm run build.types
npm run build.client
npm run build.server
npm run lint


> build.client
> vite build

vite v4.2.1 building for production...
transforming...
✓ 416 modules transformed.
Generated an empty chunk: "index".
rendering chunks...
computing gzip size...
dist/q-manifest.json        31.83 kB
dist/build/q-be1ef3a5.css   20.37 kB │ gzip:  4.27 kB
dist/build/q-4ed993c7.js     0.00 kB │ gzip:  0.02 kB
dist/build/q-145c2fdb.js     0.06 kB │ gzip:  0.07 kB
dist/build/q-de1948d9.js     0.12 kB │ gzip:  0.13 kB
dist/build/q-9241804a.js     0.14 kB │ gzip:  0.14 kB
dist/build/q-981f34ce.js     0.19 kB │ gzip:  0.15 kB
dist/build/q-d02e3863.js     0.19 kB │ gzip:  0.15 kB
dist/build/q-7d4d4921.js     0.19 kB │ gzip:  0.15 kB
dist/build/q-19115402.js     0.29 kB │ gzip:  0.21 kB
dist/build/q-f48f4499.js     0.32 kB │ gzip:  0.22 kB
dist/build/q-9bc199ef.js     0.34 kB │ gzip:  0.24 kB
dist/build/q-f2ca3866.js     0.34 kB │ gzip:  0.23 kB
dist/build/q-7b853361.js     0.35 kB │ gzip:  0.27 kB
dist/build/q-79c7f7a6.js     0.36 kB │ gzip:  0.24 kB
dist/build/q-533d5ded.js     0.47 kB │ gzip:  0.29 kB
dist/build/q-43db3d65.js     0.49 kB │ gzip:  0.33 kB
dist/build/q-77acc581.js     0.56 kB │ gzip:  0.36 kB
dist/build/q-c6253c22.js     0.68 kB │ gzip:  0.40 kB
dist/build/q-9844a20b.js     0.76 kB │ gzip:  0.47 kB
dist/build/q-6dd29884.js     1.65 kB │ gzip:  0.76 kB
dist/build/q-31ba98bd.js     1.94 kB │ gzip:  0.91 kB
dist/build/q-ad3a09d6.js     3.15 kB │ gzip:  1.51 kB
dist/build/q-0f55dcab.js     3.31 kB │ gzip:  1.44 kB
dist/build/q-0ba119cd.js     4.41 kB │ gzip:  1.90 kB
dist/build/q-c7d75ea2.js     4.96 kB │ gzip:  1.80 kB
dist/build/q-8f1fc1d2.js     6.97 kB │ gzip:  3.32 kB
dist/build/q-8272cded.js     7.43 kB │ gzip:  2.22 kB
dist/build/q-d4c37d4b.js    46.08 kB │ gzip: 18.57 kB
dist/build/q-1d615615.js    69.58 kB │ gzip: 21.25 kB
dist/build/q-64d9c2b8.js   142.35 kB │ gzip: 42.50 kB
✓ built in 5.89s

✓ Built client modules

Error: R] Missing "./adaptors/express/vite" specifier in "@builder.io/qwik-city" package [plugin externalize-deps]

    ../../Base/Qwik/node_modules/esbuild/lib/main.js:1360:27:
      1360 │         let result = await callback({
           ╵                            ^

    at e (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:25)
    at n (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:627)
    at o (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:16076:1297)
    at resolveExportsOrImports (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:23295:20)
    at resolveDeepImport (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:23314:31)
    at tryNodeResolve (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:23000:20)
    at file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:63922:40
    at requestCallbacks.on-resolve (/Base/Qwik/node_modules/esbuild/lib/main.js:1360:28)
    at handleRequest (/Base/Qwik/node_modules/esbuild/lib/main.js:723:19)
    at handleIncomingPacket (/Base/Qwik/node_modules/esbuild/lib/main.js:745:7)

  This error came from the "onResolve" callback registered here:

    ../../Base/Qwik/node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:63911:27)
    at handlePlugins (/Base/Qwik/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Base/Qwik/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Base/Qwik/node_modules/esbuild/lib/main.js:776:5)
    at /Base/Qwik/node_modules/esbuild/lib/main.js:2163:15
    at new Promise (<anonymous>)
    at Object.build (/Base/Qwik/node_modules/esbuild/lib/main.js:2162:25)
    at build (/Base/Qwik/node_modules/esbuild/lib/main.js:2011:51)
    at bundleConfigFile (file:///Base/Qwik/node_modules/vite/dist/node/chunks/dep-79892de8.js:63875:26)

  The plugin "externalize-deps" was triggered by this import

    adaptors/express/vite.config.ts:1:326:
      1 │ ...xpressAdaptor } from '@builder.io/qwik-city/adaptors/express/vite';
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

failed to load config from /Project/SiteQwik/adaptors/express/vite.config.ts
error during build:
Error: Build failed with 1 error:
../../Base/Qwik/node_modules/esbuild/lib/main.js:1360:27: ERROR: [plugin: externalize-deps] Missing "./adaptors/express/vite" specifier in "@builder.io/qwik-city" package
    at failureErrorWithLog (/Base/Qwik/node_modules/esbuild/lib/main.js:1636:15)
    at /Base/Qwik/node_modules/esbuild/lib/main.js:1048:25
    at runOnEndCallbacks (/Base/Qwik/node_modules/esbuild/lib/main.js:1471:45)
    at buildResponseToResult (/Base/Qwik/node_modules/esbuild/lib/main.js:1046:7)
    at /Base/Qwik/node_modules/esbuild/lib/main.js:1075:16
    at responseCallbacks.<computed> (/Base/Qwik/node_modules/esbuild/lib/main.js:697:9)
    at handleIncomingPacket (/Base/Qwik/node_modules/esbuild/lib/main.js:752:9)
    at Socket.readFromStdout (/Base/Qwik/node_modules/esbuild/lib/main.js:673:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)

The command '/bin/sh -c chmod 777 /Build     && bash /Build' returned a non-zero code: 1
Error: Process completed with exit code 1.


### Reproduction

I will create it if necessary. Maybe you can guide me without a reproduction example.

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: Linux 5.19 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 7.73 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.3 - /usr/local/bin/npm
  npmPackages:
    @builder.io/partytown: ^0.7.6 => 0.7.6 
    @builder.io/qwik: ^0.100.0 => 0.100.0 
    @builder.io/qwik-city: ^0.100.0 => 0.100.0 
    @builder.io/qwik-react: ^0.5.0 => 0.5.0 
    vite: ^4.2.1 => 4.2.1
```

**Comment by lbensaad** [comment]
I think they changed the folder name from adaptors to adapters, so in your project rename that folder and also in your packages.json

**Comment by Nefcanto** [comment]
@lbensaad yep, that worked. Thank you so much for your help.
