### ISSUE TITLE
[🐞] Lint crash

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#3719]
### Which component is affected?

Qwik Runtime

### Describe the bug

Lint crashes with this error:

```
Oops! Something went wrong! :(

ESLint: 8.37.0

TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting /home/runner/work/qwik/qwik/packages/docs/src/routes/demo/events/prop-function/index.tsx:12
Rule: "qwik/valid-lexical-scope"
    at JSXAttribute (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint-plugin-qwik@0.100.0_eslint@8.37.0/node_modules/eslint-plugin-qwik/index.js:7:[15](https://github.com/BuilderIO/qwik/actions/runs/4641043945/jobs/8213611468?pr=3714#step:8:16)53)
    at ruleErrorHandler (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/linter.js:1093:28)
    at /home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/node-event-generator.js:326:[22](https://github.com/BuilderIO/qwik/actions/runs/4641043945/jobs/8213611468?pr=3714#step:8:23))
    at NodeEventGenerator.enterNode (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:[23](https://github.com/BuilderIO/qwik/actions/runs/4641043945/jobs/8213611468?pr=3714#step:8:24))
    at /home/runner/work/qwik/qwik/node_modules/.pnpm/eslint@8.37.0/node_modules/eslint/lib/linter/linter.js:11[28](https://github.com/BuilderIO/qwik/actions/runs/4641043945/jobs/8213611468?pr=3714#step:8:29):32
 ```

### Reproduction

https://github.com/BuilderIO/qwik/tree/pr-lint-error

### Steps to reproduce

SRC: https://github.com/BuilderIO/qwik/tree/pr-lint-error
Error: https://github.com/BuilderIO/qwik/actions/runs/4641043945/jobs/8213611468

Local reproduction: `pnpm rund lint.eslint`

### System Info

```shell
na
```

**Comment by mhevery** [comment]
In the same branch

```TS
import {
  component$,
  useStore,
  noSerialize,
  useVisibleTask$,
} from '@builder.io/qwik';
import Monaco from './monaco';

export default component$(() => {
  const store = useStore<{ monacoInstance: Monaco | undefined }>({
    // Don't initialize on server
    monacoInstance: undefined,
  });

  useVisibleTask$(() => {
    // Monaco is not serializable, so we can't serialize it as part of SSR
    // We can however instantiate it on the client after the component is visible
    setTimeout(() => (store.monacoInstance = noSerialize(new Monaco())), 1000);
                                   ^^^^
  });
  return <div>{store.monacoInstance ? 'Monaco is loaded' : 'loading...'}</div>;
});
```
Also fails with:
```
Seems like you are referencing "store" inside a different scope (useVisibleTask$), when this happens, Qwik needs to serialize the value, however "store.monacoInstance" is an instance of the "default" class, which is not serializable. Use a simple object literal instead.
Check out https://qwik.builder.io/docs/advanced/dollar/ for more details.eslint[qwik/valid-lexical-scope](https://qwik.builder.io/docs/advanced/dollar/)
const store: {
    monacoInstance: Monaco | undefined;
}
```

**Comment by manucorporat** [comment]
Monaco is not a valid type, since it's not serializable:
  const store = useStore<{ monacoInstance: NoSerialize<Monaco> }>({
    // Don't initialize on server
    monacoInstance: undefined,
  });

**Comment by mees-van-wel** [comment]
I'm still experiencing this bug...

```ts
type Union =
  | {
      required?: false;
      onChange$: (value: Date | null) => any;
    }
  | {
      required: true;
      onChange$: (value: Date) => any;
    };
```
In my component, this works fine
```ts
const clearHandler = $(() => {
  if (!required) return;
  onChange$(null);
});
```
But this triggers the error
```ts
const changeHandler = $(() => {
 if (onChange$) onChange$(new Date());
});
```
Error
```
TypeError: Cannot read properties of undefined (reading 'name')
Occurred while linting C:\Users\mees1\projects\qwik-ui\src\components\dateInput\dateInput.tsx:1
Rule: "qwik/valid-lexical-scope"
    at _e (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:294:1167)
    at bv (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:294:343)
    at vv (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:294:194)
    at C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:291:860
    at Array.forEach (<anonymous>)
    at y (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:291:326)
    at Array.forEach (<anonymous>)
    at y (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:291:1029)
    at Array.forEach (<anonymous>)
    at y (C:\Users\mees1\projects\qwik-ui\node_modules\.pnpm\eslint-plugin-qwik@1.2.15_eslint@8.51.0\node_modules\eslint-plugin-qwik\index.js:291:1029) {
  ruleId: 'qwik/valid-lexical-scope',
  currentNode: {
    type: 'Program',
    body: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    comments: [],
    range: [ 0, 3666 ],
    sourceType: 'module',
    tokens: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 618 more items
    ],
    loc: { start: [Object], end: [Object] },
    parent: null
  }
}
```
