### ISSUE TITLE
[🐞] Using Dynamic components with signals does not work.

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#4029]
### Which component is affected?

Qwik Runtime

### Describe the bug

I would expect this to work:

```typescript
import { component$, useSignal, Component } from '@builder.io/qwik';

export default component$(() => {
  const Comp = useSignal<any>(CompA);
  return (
    <>
      <button onClick$={() => (Comp.value = CompB)}>click</button>
      <Comp.value />
    </>
  );
});

export const CompA = component$(() => <div>CompA</div>);
export const CompB = component$(() => <div>CompB</div>);
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-ranehd

### Steps to reproduce

Navigate and see the exception:

```
QWIK ERROR Error: The Qwik Component was not invocated correctly
    at createError (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:209:17)
    at logError (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:203:54)
    at logErrorAndStop (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:213:17)
    at assertNumber (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:495:15)
    at QwikComponent (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:8279:9)
    at invoke (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:1557:26)
    at Proxy.useSignal (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:9079:46)
    at AsyncFunction.routes_component_xYL1qOwPyDI (/home/projects/qwik-starter-ranehd/src/routes/index.tsx:18:40)
    at AsyncFunction.invoke (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:1557:26)
    at eval (file://file:///home/projects/qwik-starter-ranehd/node_modules/@builder.io/qwik/core.mjs:8029:35)
 ```

### System Info

```shell
na
```

**Comment by manucorporat** [comment]
Interesting! it should work as far as i can see, i will look into the compiler output!

**Comment by manucorporat** [comment]
Ok, the problem is that a Component is indeed a function, so `useSignal()` confuses it with `useSignal(() => {...})`. it's solvable
