### ISSUE TITLE
[🐞] styled component doesn't work in prod

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#4436]
### Which component is affected?

Qwik Runtime

### Describe the bug

See https://github.com/wmertens/styled-vanilla-extract/issues/15#issuecomment-1581981137 for an analysis

### Reproduction

~https://stackblitz.com/edit/qwik-starter-wadzsa?file=src/routes/index.tsx~

https://stackblitz.com/edit/qwik-starter-8kdqva?file=package-lock.json,package.json

### Steps to reproduce

notice the adapter for a static site, but disabling it doesn't make a difference.

running in dev mode it works fine. Running in preview, the styled component disappears.

Upgrading qwik to 1.1.5 and styled to 5.5.0-0 doesn't help.

However, with qwik 0.100.0 it does work!

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.1.5 => 1.1.5 
    @builder.io/qwik-city: ^1.0.0 => 1.1.5 
    undici: ^5.22.1 => 5.22.1 
    vite: ^4.3.9 => 4.3.9
```

**Comment by wmertens** [comment]
Good point I'll make a smaller repro

**Comment by wmertens** [comment]
@manucorporat I can't reproduce it without styled :confused:

Here's a blitz where I only copied the generated styled function: https://stackblitz.com/edit/qwik-starter-cegi5j?file=src%2Froutes%2Findex.tsx,src%2Froutes%2Flite.tsx,src%2Froutes%2Fverylite.tsx,src%2Froutes%2Fstyled.js

it work both normally and in preview. So something about importing styled components, or about the code changing during the build makes it fail?

**Comment by wmertens** [comment]
The only difference I can see is that it embeds `styled` into the render function, which is fine of course. When it's a node module, it doesn't do that apparently?

```tsx
import { component$ } from '@builder.io/qwik';
import { Lite } from './lite';
import { StyledH1, Very } from './verylite';

export default component$(() => {
  return (
    <>
      <h2>This shows always</h2>
      <hr />
      <Lite>This is lite but also shows always</Lite>
      <hr />
      <Very>This is one import further</Very>
      <hr />
      <StyledH1>This is a styled component</StyledH1>
    </>
  );
});
```
becomes
```js
import { d as _jsxC, f as r, g as f } from './q-b0c78d2d.js';
const makeLite = (i) => (l) => _jsxC(i, { ...l }, 0, 'Zp_0'),
  Lite = makeLite('h3'),
  styled = (Tag, myClass) => {
    const LiteCmp = ({ class: o, ...h }) => {
      let t;
      return (
        ((s) => {
          s &&
            (t || (t = [myClass]),
            typeof s == 'object'
              ? t.push(
                  Object.entries(s)
                    .filter(([, u]) => u)
                    .map(([u]) => u)
                    .join(' ')
                )
              : t.push(s));
        })(o),
        _jsxC(Tag, { ...h, class: o ? [myClass, o] : myClass }, 0, '9E_0')
      );
    };
    return (
      (LiteCmp.class = myClass),
      Object.defineProperty(LiteCmp, 'className', { get: () => myClass, enumerable: !1 }),
      (LiteCmp.toString = () => myClass),
      LiteCmp
    );
  },
  Very = makeLite('h2'),
  StyledH1 = styled('h1', 'foo'),
  H = () =>
    _jsxC(
      f,
      {
        children: [
          r('h2', null, null, 'This shows always', 3, null),
          r('hr', null, null, null, 3, null),
          _jsxC(Lite, { children: 'This is lite but also shows always' }, 3, 'H1_0'),
          r('hr', null, null, null, 3, null),
          _jsxC(Very, { children: 'This is one import further' }, 3, 'H1_1'),
          r('hr', null, null, null, 3, null),
          _jsxC(StyledH1, { children: 'This is a styled component' }, 3, 'H1_2'),
        ],
      },
      1,
      'H1_3'
    );
export { H as s_xYL1qOwPyDI };
```

@manucorporat In the failing repro in dev mode, it does say `QWIK WARN Duplicate implementations of "JSXNode" found`. Maybe that's related?

**Comment by wmertens** [comment]
@manucorporat I instrumented qwik core.*js and when I run `nps run dev`, it loads both the regular and the dev version.

Can it be that the styled-components gets the prod version?

```
Error: hi from core.mjs
    at eval (/node_modules/@builder.io/qwik/core.mjs:4:15)
    at async instantiateModule (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:54396:9)
Error: hi from core.prod.mjs
    at eval (file:///home/projects/qwik-starter-lnnrsl/src/components/ui/title.css.ts:39:15)
    at Proxy.<anonymous> (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:1:195)
    at __global_eval__ (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:1:241)
    at _0x49076a (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:44:149088)
    at Script.runInContext (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:44:148624)
    at Script.runInContext (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:35:395895)
    at Script.runInNewContext (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:35:396003)
    at module.exports [as default] (file:///home/projects/qwik-starter-lnnrsl/node_modules/eval/eval.js:74:12)
    at Object.processVanillaFile (file:///home/projects/qwik-starter-lnnrsl/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.dev.js:132:50)
    at TransformContext.transform (file:///home/projects/qwik-starter-lnnrsl/node_modules/styled-vanilla-extract/lib/vite.cjs:187:38)
    at async Object.transform (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:42929:30)
    at async loadAndTransform (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:53386:29)
Error: hi from core.prod.mjs
    at eval (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/@builder.io/qwik/core.prod.mjs:94:15)
    at Generator.next (<anonymous>)
    at _0x5b3f55.run (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:44:307397)
    at _0x8a4b23._evaluate (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:44:312841)
    at async _0x8a4b23._evaluate (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:44:312740)
    at async ModuleJob.run (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:35:1078076)
    at async Promise.all (index 0)
    at async ESMLoader.import (https://qwikstarterlnnrsl-251f.w-credentialless.staticblitz.com/blitz.bf38680a.js:35:1312912)
    at async nodeImport (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:54441:17)
    at async ssrImport (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:54334:24)
    at async eval (/src/components/ui/title.css.ts:4:31)
    at async instantiateModule (file://file:///home/projects/qwik-starter-lnnrsl/node_modules/vite/dist/node/chunks/dep-a178814b.js:54396:9)
QWIK WARN Duplicate implementations of "JSXNode" found
QWIK WARN Duplicate implementations of "JSXNode" found
```

**Comment by manucorporat** [comment]
Yeah that’s bad… I have an idea why this is happening! Node resolution is not the same as Vite resolution.

**Comment by wmertens** [comment]
@manucorporat are you closer to solving this?

**Comment by wmertens** [comment]
Oh and qwikest/icons also has this problem but it doesn't use a vite transform so that's not the cause

**Comment by wmertens** [comment]
@manucorporat could it be because of .mjs and .js leading to two different qwik instances?

**Comment by wmertens** [comment]
Not because of mjs/js because I was able to reproduce this in the playground :sunglasses:

The one weird thing I'm doing is passing JsxNodes to an inline component:

https://qwik.builder.io/playground/#v=1.1.5&f=7VbBTsMwDP2V0AudNqXbbkATiSN3bhOHVVrFJCTQCocpyr%2Fznp1kbeEARyQmrU1T%2B9nPdh2PiuZmXeiMi2ZlWMc5zNU8LdWc6uO%2BG0gVGOyZiKmJhfaxN%2FXV%2Fem0P9vjIPc6Sy0WFwVndnn9dAc1RX5X5N1oC6PD4eWyib6c%2Bpkza27gMDO1igqgee2LFU29%2BiR7VqrROYf2Atj8PtvCYMKJB5FwikED%2FKkT9u1jeAZra628XeUBSbZkjXpn%2Bm4NTqpDj4YJIXU3IkYZjjQVrEUsVcAFuUUfBMgKTmwbCHgoJk2RWS4VKOLK%2F7TSOMQl6UBDlJAHJaGPOuuVGpmnl%2FxH3SFkDpJlsfBwjRECgslrPR8T95bl1Hi1AQMTdAn8z%2FDp8NQAjyGofDXxm96W4sQqLt%2BOeiX%2Bu4q8NpXXvU3byOJb0dB2ntJbDCjdGV%2Bgj0ltO1GTNIo1xvu%2Fkf7JRvoJ

**Comment by wmertens** [comment]
Actually, false alert, I was destroying the JsxNode instance by doing {...child}. When I instead do

```tsx
      child.props = { ...props, title: undefined, index }
      panels.push(child);
```

it's fine.

**Comment by wmertens** [comment]
Note that I tried editing the package.json of styled-vanilla-extract to have only the ESM entries, and it still happened, so I don't think it's because of ESM+require coexisting.

**Comment by wmertens** [comment]
fixed in https://github.com/wmertens/styled-vanilla-extract/commit/272e8c5466082a57d95e1fe76d80241aa830ab18
