### ISSUE TITLE
[🐞]

### ISSUE THREAD

**Issue by abdullhakim-sami** [BuilderIO/qwik#4645]
### Which component is affected?

Starters / CLI

### Describe the bug

// How to reproduce?
use create qwik@latest

npm start
pnpm start
yarn start

on windows 11 fresh install :

it dosen't run correctly..

> my-qwik-basic-starter@ start C:\Coding\Qwik\KemoTVT
> vite --open --mode ssr

Error: The specified module could not be found.
\\?\C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\bindings\qwik.win32-x64-msvc.node
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at sys.dynamicImport (C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\optimizer.cjs:1197:35)
    at loadPlatformBinding (C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\optimizer.cjs:1280:37)
    at createOptimizer (C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\optimizer.cjs:1355:93)
    at async Object.init2 [as init] (C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\optimizer.cjs:1703:49)
    at async config (C:\Coding\Qwik\KemoTVT\node_modules\.pnpm\@builder.io+qwik@1.2.1_undici@5.22.1\node_modules\@builder.io\qwik\optimizer.cjs:2988:9) {
  code: 'ERR_DLOPEN_FAILED'
}

//// How to fix it ??

do this:

The issue is because the package is failing due to a missing library on the computer. fs-search requires Microsoft Visual C++ 2015 Redistributable (x64).

/// What next?

 Add this to the docs cuz its important ig ?

### Reproduction

.

### System Info

```shell
windows 11
```

### Additional Information

.

**Comment by nsdonato** [comment]
Hey @abdullhakim-sami  There was a fix in version 1.2.2 for the CLI, I don't know if it's related, but can you test if it's still a problem? I have Mac 😅

**Comment by manucorporat** [comment]
I can see this issue happening in the CI. Windows is so frustrating :(

**Comment by manucorporat** [comment]
I think this was fixed! https://github.com/BuilderIO/qwik/commit/0f908f31f93039a17f10e67af464ad93eb987523
