### ISSUE TITLE
[🐞] ERR_STREAM_DESTROYED on Qwik 1.2.0+

### ISSUE THREAD

**Issue by tanftw** [BuilderIO/qwik#4651]
### Which component is affected?

Qwik Runtime

### Describe the bug

After upgrading to Qwik 1.2.0+ all of the server stream features broke and returned ERR_STREAM_DESTROYED error code.
I have tried to remove `node_modules` and reinstall but still got the error. Rolled back to 1.1.5 works!

### Reproduction

https://stackblitz.com/edit/qwik-starter-lzajtq?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Here is the minimal example which works on the previous version but error on 1.2+

```tsx
import { component$, useVisibleTask$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";
import { server$ } from "@builder.io/qwik-city";
const wait = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

const stream = server$(async function* () {
  while (true) {
    yield "hey";
    await wait(1000);
  }
});

export default component$(() => {
  useVisibleTask$(() => {
    (async () => {
      for await (const message of await stream()) {
        console.log(message);
      }
    })();
  });

  return <div>Get Messages</div>;
});

export const head: DocumentHead = {
  title: "Index",
};
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 11.25 GB / 15.59 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.3.0 - /mnt/wslg/runtime-dir/fnm_multishells/29104_1688098836356/bin/node
    Yarn: 1.22.19 - /mnt/wslg/runtime-dir/fnm_multishells/29104_1688098836356/bin/yarn
    npm: 9.6.4 - /mnt/wslg/runtime-dir/fnm_multishells/29104_1688098836356/bin/npm
    pnpm: 8.6.3 - /mnt/wslg/runtime-dir/fnm_multishells/29104_1688098836356/bin/pnpm
  npmPackages:
    @builder.io/qwik: 1.2.0 => 1.2.0
    @builder.io/qwik-city: 1.2.0 => 1.2.0
    undici: 5.22.0 => 5.22.0
    vite: ^4.3.9 => 4.3.9
```

### Additional Information

Here is the error in the console:
```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node: internal/errors:400:5)
    at write_ (node:_http_outgoing:870:11)
    at ServerResponse.write (node:_http_outgoing:827:15)
    at Object.write (/home/tan/Sites/R3/node_modules/@builder.io/qwik-city/vite/index.cjs:24747:15)
    at ensureIsPromise (node:internal/webstreams/util:190:19)
    at writableStreamDefaultControllerProcessWrite (node: internal/webstreams/writablestream:1085:5)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1200:5)
    at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1074:3)
    at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:963:3)
    at WritableStreamDefaultWriter.write (node:internal/webstreams/writablestream:474:12) {
  code: 'ERR_STREAM_DESTROYED'
}
```

**Comment by manucorporat** [comment]
Is this happening in the dev server (vite), or when deploying?

**Comment by tanftw** [comment]
I have checked and see it only happening in the dev server.

**Comment by barbalex** [comment]
I have similar error:
```
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at new NodeError (node:internal/errors:399:5)
    at write_ (node:_http_outgoing:892:11)
    at ServerResponse.write (node:_http_outgoing:849:15)
    at Object.write (C:\Users\alexa\bb4\node_modules\@builder.io\qwik-city\vite\index.cjs:24755:15)
    at ensureIsPromise (node:internal/webstreams/util:192:19)
    at writableStreamDefaultControllerProcessWrite (node:internal/webstreams/writablestream:1112:5)
    at writableStreamDefaultControllerAdvanceQueueIfNeeded (node:internal/webstreams/writablestream:1227:5)
    at writableStreamDefaultControllerWrite (node:internal/webstreams/writablestream:1101:3)
    at writableStreamDefaultWriterWrite (node:internal/webstreams/writablestream:991:3)
    at WritableStreamDefaultWriter.write (node:internal/webstreams/writablestream:497:12) {
  code: 'ERR_STREAM_DESTROYED'
}
11:47:31 [vite] Internal server error: aborted
      at connResetException (node:internal/errors:717:14)
      at abortIncoming (node:_http_server:754:17)
      at socketOnClose (node:_http_server:748:3)
      at Socket.emit (node:events:525:35)
      at TCP.<anonymous> (node:net:322:12)
```

But in my case it is caused by a regular server side update:
```js
const adder = server$(async function (id) {
  try {
    const queryRes = await db.query(
      `select links
       from event
       where id = $1`,
      [id],
    )
    const links = queryRes?.rows[0]?.links ?? []
    const newLinks = [...links, { url: '', label: '' }]
    console.log('newLinks', { id, newLinks })
    // need to stringify the links array because of pg converts objects but not arrays:
    // https://github.com/brianc/node-postgres/issues/374
    await db.query(
      `update event
        set links = $2
        where id = $1`,
      [id, JSON.stringify(newLinks)],
    )
  } catch (error) {
    console.error('query error', {
      stack: error.stack,
      message: error.message,
    })
  }
  console.log('links, adder will return')
  return true
})
```

It only happens in dev. I develop on Windows 11.

**Comment by genki** [comment]
This is still happening randomly on qwik 1.5.6

**Comment by wmertens** [comment]
@genki can you try on latest node? Only dev mode right?

**Comment by PatrickJS** [comment]
can you make a new issue with reproduction repo then I can fix it

**Comment by genki** [comment]
@wmertens 
I am using `qwik 1.5.6-dev20240611011722`. Something affecting has changed after this?

@PatrickJS 
This is happening only on the dev mode at least in my case.
I can make a new issue but I can't provide any new information that helps to solve.
This is very hard to reproduce because this is happening quite randomly after the long time opening the browser tab.
Typically I face this issue after the come back from leaving it for going to the bed.
If it is no matter, I will.
<img width="487" alt="スクリーンショット 2024-06-15 2 18 41（2）" src="https://github.com/QwikDev/qwik/assets/4876/796f5b78-d464-4b32-86b8-dd240860fdde">
