### ISSUE TITLE
[🐞] error during build: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by vr10t** [BuilderIO/qwik#4850]
### Which component is affected?

Qwik React

### Describe the bug

Error while building for deployment, caused by Vidstack Player (using React). Building without adapters and for preview works perfectly fine, however trying to build for server always fails with the same error: `document is not defined`.

<details>
<summary>Stack trace</summary>

> 

18:52:52.646 | error during build:
-- | --
18:52:52.646 | ReferenceError: document is not defined
18:52:52.647 | at uc (file:///opt/buildhome/repo/server/assets/@qwik-city-plan-2781a0b7.js:57:6997)
18:52:52.647 | at file:///opt/buildhome/repo/server/assets/@qwik-city-plan-2781a0b7.js:57:8850
18:52:52.647 | at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
18:52:52.647 | at async Promise.all (index 0)
18:52:52.647 | at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
18:52:52.647 | at async createSingleThreadWorker (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:124:14)
18:52:52.647 | at async createNodeMainProcess (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:375:30)
18:52:52.647 | at async mainThread (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:882:16)
18:52:52.648 | at async Module.generate (file:///opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/node.mjs:1074:20)
18:52:52.648 | at async Module.generate (/opt/buildhome/repo/node_modules/@builder.io/qwik-city/static/index.cjs:28:18)
18:52:52.648 |  
18:52:52.670 | Failed: Error while executing user command. Exited with error code: 1
18:52:52.680 | Failed: build command exited with code: 1
18:52:53.836 | Failed: error occurred while running build command

</details>

### Reproduction

https://stackblitz.com/edit/qwik-starter-g3ylmq?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Run `npm run build`

### System Info

```shell
@builder.io/qwik: ^1.2.6 => 1.2.6
 @builder.io/qwik-city: ^1.2.6 => 1.2.6
 @builder.io/qwik-react: 0.5.0 => 0.5.0
 undici: 5.22.1 => 5.22.1
 vite: 4.4.0 => 4.4.0
```

**Comment by vr10t** [comment]
Ok, after implementing Vidstack using vanilla js it still gives the same error, so React isn't the issue. I discovered that deploying with express works fine though so I'm not sure what to make of it.

**Comment by vr10t** [comment]
While it does build when deploying it with Express, the app throws a runtime error while loading the player: `QWIK ERROR Error: Code(10)`. I could not find anywhere what this means, but after some digging I found out that Qwik does not support Web Components, which Vidstack uses, which means this is related to #1714.
