### ISSUE TITLE
[🐞] qwik add pandacss eats my homework

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#4863]
### Which component is affected?

Starters / CLI

### Describe the bug

I created a new qwik app with `pnpm create qwik@latest`, did some changes, updates, and then did `qwik add pandacss`. This gives the following output and sets all the files it's changing to 0 bytes:

### Reproduction

The problem is that it works in stackblitz. It also complains but it doesn't clear the files.

### Steps to reproduce

```
> qwik add pandacss

┌  🦋  Add Integration  pandacss
TypeError: updatedContent.replace is not a function
    at updateViteConfigs (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2468:43)
    at async updateApp (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2505:5)
    at async runAddInteractive (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2610:18)
    at async runAddCommand (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2748:7)
    at async runCommand2 (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:4674:7)
    at async Object.runCli (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:4666:5)
│
◇  👻  Ready?  Add pandacss to your app?
│
│  🐬 Modify
│     - package.json
│     - .eslintignore
│     - .prettierignore
│     - .gitignore
│     - src/global.css
│     - vite.config.ts
│
│  🌟 Create
│     - postcss.config.js
│     - panda.config.ts
│     - src/routes/pandacss/index.tsx
│
│  💾 Install npm dependencies:
│     - @builder.io/vite-plugin-macro ~0.0.7
│     - @pandacss/dev ^0.4.0
│
│  📜 New npm scripts:
│     - npm run prebuild.pandacss
│
◇  Ready to apply the pandacss updates to your app?
│  Yes looks good, finish update!
│
○  Updating app and installing dependencies
/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/plugins/flow.js:4
`),x.js_error)throw x.js_error}}else throw x}function tZ(){var x=l0.process;x&&x.on?x.on("uncaughtException",function(r,e){DK(r),x.exit(2)}):l0.addEventListener&&l0.addEventListener("error",function(r){r.error&&DK(r.error)})}tZ();function l(x,r){return(x.l>=0?x.l:x.l=x.length)==1?x(r):Ds(x,[r])}function p(x,r,e){return(x.l>=0?x.l:x.l=x.length)==2?x(r,e):Ds(x,[r,e])}function G0(x,r,e,t){return(x.l>=0?x.l:x.l=x.length)==3?x(r,e,t):Ds(x,[r,e,t])}function oe(x,r,e,t,u){return(x.l>=0?x.l:x.l=x.length)==4?x(r,e,t,u):Ds(x,[r,e,t,u])}function Je(x,r,e,t,u,i){return(x.l>=0?x.l:x.l=x.length)==5?x(r,e,t,u,i):Ds(x,[r,e,t,u,i])}function nZ(x,r,e,t,u,i,f,o){return(x.l>=0?x.l:x.l=x.length)==7?x(r,e,t,u,i,f,o):Ds(x,[r,e,t,u,i,f,o])}var qC=[Qr,jz,-1],jK=[Qr,az,-2],mn=[Qr,q_,-3],GC=[Qr,rz,-4],w2=[Qr,dD,-7],zK=[Qr,Ij,-8],KK=[Qr,aj,-9],Tr=[Qr,YU,-11],Il=[Qr,Dj,-12],uZ=[4,0,0,0,[12,45,[4,0,0,0,0]]],bC=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,ij,[4,0,0,0,[12,45,[4,0,0,0,[11,": ",[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'],Ja=[0,0,[0,0,0],[0,0,0]],Pl=[0,0,0,0,1,0,0,0],JK=[0,"first_leading","last_trailing"],YK=[0,hf,gf,ni,l7,Af,Ii,yu,uc,O7,zi,Nf,un,Ku,sc,Le,E7,Q7,rf,Bf,T7,ci,Xc,hc,Gn,uf,j7,ku,ji,Qi,Jc,B7,Tu,yi,bi,_i,fi,Ff,Xi,nu,s7,Bc,K7,Wu,mc,vi,tf,Wf,Wn,ic,oc,Fi,Ce,Re,Mu,lf,dc,Mi,y7,Pf,ju,Gf,sf,ec,Tf,_c,Ai,ce,Ri,qn,ff,Hi,_u,e7,Iu,Li,xf,kc,cc,gu,Uu,ef,p7,$n,_f,v7,zf,z7,Q1,pi,Zu,Zn,J7,o7,Cf,df,V7,xu,Ci,Ru,wu,iu,Vu,xc,F7,jn,nc,d7,Yn,R7,Qu,Fu,If,Gu,af,zn,ki,jc,Yi,lu,mi,ou,Su,It,k7,t7,_7,R2,di,eu,Du,c7,of,cu,jf,A7,F2,Hu,Qn,Mf,Di,uu,Wc,G7,au,F1,Ui,Ju,Sc,tc,x7,yf,du,xi,Mc,ui,C7,n7,q7,Vn,Zf,Vf,$i,qf,L7,Ou,Bn,Ni,P7,Kn,tu,qi,xr,u7,ii,Cu,yc,$u,i7,Cc,Nc,zu,Ac,Y7,mf,g7,Pi,Of,Yf,ru,Wi,Dc,nf,Oc,r7,ti,kf,ei,bf,si,H7,Qf,bn,Yu,Sf,pn,Pc,Au,D7,vc,wc,S7,X7,Lu,f7,a7,Oi,Nu,fc,$f,b7,Df,zc,mu,Uf,ac,su,je,pc,fu,Pu,pu,Zi,I7,Me,lc,Xu,N7,Tc,Ji,Bi,m7,Gi,Ke,Eu,Z7,Rf,pf,gc,Si,wf,ze,Kc,cf,Ki,hu,rc,Xn,Fn,hi,Kf,li,Rc,h7,Lc,ai,Jn,M7,Ti,Xf,Jf,$7,w7,U7,oi,Bu,Ec,Hn,W7,qu,Yc,Ei,L2,Lf,vf,ri,U2],kn=[0,0,0];Dt(11,Il,Dj),Dt(10,Tr,YU),Dt(9,[Qr,TD,PM],TD),Dt(8,KK,aj),Dt(7,zK,Ij),Dt(6,w2,dD),Dt(5,[Qr,qM,-6],qM),Dt(4,[Qr,tM,-5],tM),Dt(3,GC,rz),Dt(2,mn,q_),Dt(1,jK,az),Dt(0,qC,jz);var iZ="output_substring",fZ=Hf,cZ=Ts,sZ=As,oZ="CamlinternalLazy.Undefined",vZ=mz,aZ="\\'",lZ="\\b",pZ="\\t",yZ="\\n",dZ="\\r",mZ="List.iter2",kZ="tl",hZ="hd",_Z="String.blit / Bytes.blit_string",wZ="Bytes.blit",TZ="String.sub / Bytes.sub",SZ="Array.blit",EZ="Array.sub",AZ="Map.remove_min_elt",gZ=[0,0,0,0],NZ=[0,"map.ml",400,10],IZ=[0,0,0],PZ=K4,CZ=K4,RZ=K4,OZ=K4,LZ="Stdlib.Queue.Empty",UZ="Buffer.add_substring/add_subbytes",MZ="Buffer.add: cannot grow buffer",DZ=[0,GU,93,2],jZ=[0,GU,94,2],zZ="Buffer.sub",KZ="%c",JZ="%s",YZ=DU,BZ=dz,XZ=vD,WZ=Uz,VZ="%f",ZZ="%B",$Z="%{",FZ="%}",QZ="%(",HZ="%)",qZ=CD,GZ="%t",bZ="%?",x$="%r",r$="%_r",e$=[0,i2,850,23],t$=[0,i2,814,21],n$=[0,i2,815,21],u$=[0,i2,818,21],i$=[0,i2,819,21],f$=[0,i2,822,19],c$=[0,i2,823,19],s$=[0,i2,826,22],o$=[0,i2,827,22],v$=[0,i2,831,30],a$=[0,i2,832,30],l$=[0,i2,836,26],p$=[0,i2,837,26],y$=[0,i2,846,28],d$=[0,i2,847,28],m$=[0,i2,851,23],k$=[0,i2,1558,4],h$="Printf: bad conversion %[",_$=[0,i2,1626,39],w$=[0,i2,1649,31],T$=[0,i2,1650,31],S$="Printf: bad conversion %_",E$=Oj,A$=aD,g$=Oj,N$=aD,I$=[0,[11,"invalid box description ",[3,0,0]],"invalid box description %S"],P$=[0,0,4],C$=jk,R$="neg_infinity",O$=_D,L$=Hf,U$=[0,tt],M$="%+nd",D$="% nd",j$="%+ni",z$="% ni",K$="%nx",J$="%#nx",Y$="%nX",B$="%#nX",X$="%no",W$="%#no",V$="%nd",Z$=vD,$$="%nu",F$="%+ld",Q$="% ld",H$="%+li",q$="% li",G$="%lx",b$="%#lx",xF="%lX",rF="%#lX",eF="%lo",tF="%#lo",nF="%ld",uF=dz,iF="%lu",fF="%+Ld",cF="% Ld",sF="%+Li",oF="% Li",vF="%Lx",aF="%#Lx",lF="%LX",pF="%#LX",yF="%Lo",dF="%#Lo",mF="%Ld",kF=Uz,hF="%Lu",_F="%+d",wF="% d",TF="%+i",SF="% i",EF="%x",AF="%#x",gF="%X",NF="%#X",IF="%o",PF="%#o",CF=hl,RF=DU,OF=qD,LF=oa,UF="@}",MF="@?",DF=`@
                                     ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Promise
    at Object.writeFile (node:internal/fs/promises:866:5)
    at /home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2524:50
    at Array.map (<anonymous>)
    at Object.commit (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2523:27)
    at runAddInteractive (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2616:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runAddCommand (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:2748:7)
    at async runCommand2 (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:4674:7)
    at async Object.runCli (/home/wmertens/Projects/DropOn/tracy-v2/node_modules/.pnpm/@builder.io+qwik@1.2.6_undici@5.22.1/node_modules/@builder.io/qwik/cli.cjs:4666:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.14.1
```

### System Info

```shell
System:
    OS: Linux 6.1 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 4.07 GB / 15.20 GB
    Container: Yes
    Shell: 5.2.15 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.14.1 - /nix/store/0dfsknf96ww7x6lb76apyzimfijnqhvm-nodejs-18.14.1/bin/node
    Yarn: 1.22.19 - ~/bin/yarn
    npm: 9.3.1 - /nix/store/0dfsknf96ww7x6lb76apyzimfijnqhvm-nodejs-18.14.1/bin/npm
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by manucorporat** [comment]
it's caused by prettier 3.0, i will fix, but can be workaround by downgrading prettier to 2.x
