### ISSUE TITLE
[🐞] Application does not run

### ISSUE THREAD

**Issue by saengraciaEspe** [BuilderIO/qwik#4886]
### Which component is affected?

Qwik Runtime

### Describe the bug

The error I get is the following, this happens when I run the application with npm start:

error when starting dev server:
Error: 
Something went wrong installing the "sharp" module

Cannot find module '../build/Release/sharp-win32-x64.node'
Require stack:
- C:\Users\SteevenE\Documents\source_code\my_projects\mystore - qwik\mystore-frontend\node_modules\sharp\lib\sharp.js
- C:\Users\SteevenE\Documents\source_code\my_projects\mystore - qwik\mystore-frontend\node_modules\sharp\lib\constructor.js
- C:\Users\SteevenE\Documents\source_code\my_projects\mystore - qwik\mystore-frontend\node_modules\sharp\lib\index.js

Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current win32-x64 runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\Users\SteevenE\Documents\source_code\my_projects\mystore - qwik\mystore-frontend\node_modules\sharp\lib\sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\SteevenE\Documents\source_code\my_projects\mystore - qwik\mystore-frontend\node_modules\sharp\lib\constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

### Reproduction

Is in my computer personal

### Steps to reproduce

Create a new qwik project, with the recommended option. During the installation process I chose to install the dependencies. After it was finished I ran the npm start command

### System Info

```shell
Windows 10, Node version 18.16.0
```

**Comment by DeVoresyah** [comment]
same issue

**Comment by mhevery** [comment]
Sorry, but we need a reproduction, It Works on my machine... 🤷

**Comment by dengaojian** [comment]
same issue， Running locally is okay, but installing on PAAS will result in an error message

**Comment by primozs** [comment]
i have the same issue yarn1 and latest pnpm.
pnpm sometimes works but rm -rf node_modules, pnpm install, at this moment does not work for me.
Ubuntu 22.04.3 LTS
node v20.10.0
nvm 0.38.0

**Comment by primozs** [comment]
for me solution is: "postinstall": "pnpm install sharp"

**Comment by DeVoresyah** [comment]
> Sorry, but we need a reproduction, It Works on my machine... 🤷

This is the error log that I got from deploying on cloudflare pages, hope can help:
```
2023-12-15T06:09:42.429787Z	Cloning repository...
2023-12-15T06:09:43.774867Z	From https://github.com/Cuan-sh/cuan-landing
2023-12-15T06:09:43.775518Z	 * branch            cee3192a63fd61d8a50609b80b48b79ffbe67c7e -> FETCH_HEAD
2023-12-15T06:09:43.775706Z	
2023-12-15T06:09:43.937318Z	HEAD is now at cee3192 fix: bun lock
2023-12-15T06:09:43.938003Z	
2023-12-15T06:09:44.043899Z	
2023-12-15T06:09:44.079632Z	Success: Finished cloning repository files
2023-12-15T06:09:44.867602Z	Detected the following tools from environment: nodejs@16.20.2, bun@1.0.1
2023-12-15T06:09:44.868874Z	Installing nodejs 16.20.2
2023-12-15T06:09:44.963319Z	nodejs 16.20.2 is already installed
2023-12-15T06:09:45.583354Z	Installing project dependencies: bun install --frozen-lockfile
2023-12-15T06:09:45.863875Z	bun install v1.0.1 (31aec4eb)
2023-12-15T06:09:57.812996Z	 + @builder.io/qwik@1.2.17
2023-12-15T06:09:57.813492Z	 + @builder.io/qwik-city@1.2.17
2023-12-15T06:09:57.813694Z	 + @storybook/addon-essentials@7.5.3
2023-12-15T06:09:57.813835Z	 + @storybook/addon-links@7.5.3
2023-12-15T06:09:57.813966Z	 + @storybook/blocks@7.5.3
2023-12-15T06:09:57.814093Z	 + @storybook/builder-vite@7.5.3
2023-12-15T06:09:57.814243Z	 + @storybook/html@7.5.3
2023-12-15T06:09:57.81437Z	 + @storybook/html-vite@7.5.3
2023-12-15T06:09:57.814514Z	 + @types/eslint@8.44.7
2023-12-15T06:09:57.814648Z	 + @types/node@20.9.0
2023-12-15T06:09:57.814785Z	 + @typescript-eslint/eslint-plugin@6.11.0
2023-12-15T06:09:57.81493Z	 + @typescript-eslint/parser@6.11.0
2023-12-15T06:09:57.815068Z	 + autoprefixer@10.4.16
2023-12-15T06:09:57.815222Z	 + eslint@8.53.0
2023-12-15T06:09:57.815357Z	 + eslint-plugin-qwik@1.2.17
2023-12-15T06:09:57.815485Z	 + postcss@8.4.31
2023-12-15T06:09:57.815615Z	 + prettier@3.1.0
2023-12-15T06:09:57.81575Z	 + prettier-plugin-tailwindcss@0.5.7
2023-12-15T06:09:57.815876Z	 + storybook@7.5.3
2023-12-15T06:09:57.815999Z	 + storybook-framework-qwik@0.2.4
2023-12-15T06:09:57.816122Z	 + tailwindcss@3.3.3
2023-12-15T06:09:57.816287Z	 + typescript@5.2.2
2023-12-15T06:09:57.816441Z	 + undici@5.27.2
2023-12-15T06:09:57.816588Z	 + vite@4.5.0
2023-12-15T06:09:57.816759Z	 + vite-tsconfig-paths@4.2.1
2023-12-15T06:09:57.816903Z	 + wrangler@3.20.0
2023-12-15T06:09:57.818222Z	 + @fontsource-variable/inter@5.0.15
2023-12-15T06:09:57.818565Z	 + @qwikest/icons@0.0.13
2023-12-15T06:09:57.818972Z	 + remixicon@3.5.0
2023-12-15T06:09:57.819271Z	
2023-12-15T06:09:57.81953Z	 1121 packages installed [11.96s]
2023-12-15T06:09:57.833987Z	Executing user command: bun run build
2023-12-15T06:09:58.159034Z	$ qwik build
2023-12-15T06:09:58.495711Z	
2023-12-15T06:09:58.496149Z	      ............
2023-12-15T06:09:58.496422Z	    .::: :--------:.
2023-12-15T06:09:58.496645Z	   .::::  .:-------:.
2023-12-15T06:09:58.496884Z	  .:::::.   .:-------.
2023-12-15T06:09:58.497094Z	  ::::::.     .:------.
2023-12-15T06:09:58.497488Z	 ::::::.        :-----:
2023-12-15T06:09:58.497768Z	 ::::::.       .:-----.
2023-12-15T06:09:58.498044Z	  :::::::.     .-----.
2023-12-15T06:09:58.498214Z	   ::::::::..   ---:.
2023-12-15T06:09:58.498347Z	    .:::::::::. :-:.
2023-12-15T06:09:58.498478Z	     ..::::::::::::
2023-12-15T06:09:58.49862Z	             ...::::
2023-12-15T06:09:58.49875Z	     
2023-12-15T06:09:58.49888Z	
2023-12-15T06:09:58.499015Z	
2023-12-15T06:09:58.499162Z	bun run build.types
2023-12-15T06:09:58.49929Z	bun run build.client
2023-12-15T06:09:58.499415Z	bun run build.server
2023-12-15T06:09:58.499537Z	bun run lint
2023-12-15T06:09:58.499669Z	
2023-12-15T06:09:58.510502Z	$ tsc --incremental --noEmit --pretty
2023-12-15T06:09:58.521313Z	$ vite build
2023-12-15T06:09:59.483071Z	[31merror during build:
2023-12-15T06:09:59.483393Z	Error: 
2023-12-15T06:09:59.483555Z	Something went wrong installing the "sharp" module
2023-12-15T06:09:59.4837Z	
2023-12-15T06:09:59.483842Z	Cannot find module '../build/Release/sharp-linux-x64.node'
2023-12-15T06:09:59.483969Z	Require stack:
2023-12-15T06:09:59.484093Z	- /opt/buildhome/repo/node_modules/sharp/lib/sharp.js
2023-12-15T06:09:59.484243Z	- /opt/buildhome/repo/node_modules/sharp/lib/constructor.js
2023-12-15T06:09:59.484371Z	- /opt/buildhome/repo/node_modules/sharp/lib/index.js
2023-12-15T06:09:59.486074Z	
2023-12-15T06:09:59.486844Z	Possible solutions:
2023-12-15T06:09:59.487325Z	- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
2023-12-15T06:09:59.488053Z	- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
2023-12-15T06:09:59.488491Z	- Consult the installation documentation: https://sharp.pixelplumbing.com/install
2023-12-15T06:09:59.488757Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/sharp.js:37:9)
2023-12-15T06:09:59.488942Z	    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-12-15T06:09:59.489076Z	    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
2023-12-15T06:09:59.48922Z	    at Module.load (node:internal/modules/cjs/loader:1076:32)
2023-12-15T06:09:59.489347Z	    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
2023-12-15T06:09:59.489472Z	    at Module.require (node:internal/modules/cjs/loader:1100:19)
2023-12-15T06:09:59.490157Z	    at require (node:internal/modules/cjs/helpers:119:18)
2023-12-15T06:09:59.49045Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/sharp/lib/constructor.js:11:1)
2023-12-15T06:09:59.490943Z	    at Module._compile (node:internal/modules/cjs/loader:1198:14)
2023-12-15T06:09:59.491316Z	    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)[39m
2023-12-15T06:09:59.513181Z	error: script "build.client" exited with code 1 (SIGHUP)
2023-12-15T06:09:59.520756Z	error: script "build" exited with code 1 (SIGHUP)
2023-12-15T06:09:59.523367Z	Failed: Error while executing user command. Exited with error code: 1
2023-12-15T06:10:02.548765Z	Failed: build command exited with code: 1
2023-12-15T06:10:06.103734Z	Failed: error occurred while running build command
```

**Comment by gioboa** [comment]
can you try this solution pls?
https://github.com/BuilderIO/qwik/issues/5556#issuecomment-1851458768
Let me know if it works for you

**Comment by DeVoresyah** [comment]
> can you try this solution pls? [#5556 (comment)](https://github.com/BuilderIO/qwik/issues/5556#issuecomment-1851458768) Let me know if it works for you

still doesn't work. should i run `bun install sharp` manually before deploying?

**Comment by gioboa** [comment]
You could try even if sharp is not Qwik direct dependency and usually these dependencies are not listed in the package.json

**Comment by DeVoresyah** [comment]
welp, still didn't work. Now I've no idea what to do :/

**Comment by gioboa** [comment]
Ok, let's close this one and we can continue in the other one please b/c it's identical
