### ISSUE TITLE
[🐞] vitest returns error when conditionally hiding qwik component

### ISSUE THREAD

**Issue by riencoertjens** [BuilderIO/qwik#4914]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

we're trying to start using vitest and I ran into this issue,
I have this [simple component](https://github.com/riencoertjens/qwik-vitest/blob/main/src/components/example/example.tsx) where a button is hidden when clicking it,
however when clicking the button in the test, the error below is shown and the component is not updated (both snapshots are the same)

the test will pass when wrapping the component with a regular html element or using a regular button element

```
QWIK ERROR TypeError: this.$template$.append is not a function
    at VirtualElementImpl.remove (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/virtual-element.js:113:20)
    at directRemoveChild (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/visitor.js:896:6)
    at _removeNode (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/operations.js:133:6)
    at executeDOMRender (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/operations.js:148:6)
    at executeContextWithScrollAndTransition (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/visitor.js:881:5)
    at renderMarked (/Users/riencoertjens/repos/qwik-vitest/dist-dev/tsc-out/packages/qwik/src/core/render/dom/notify-render.js:168:9)
    at Object.flush (/Users/riencoertjens/repos/qwik-vitest/node_modules/@builder.io/qwik/testing/index.mjs:22432:26)
    at triggerUserEvent (/Users/riencoertjens/repos/qwik-vitest/node_modules/@builder.io/qwik/testing/index.mjs:22519:3)
    at /Users/riencoertjens/repos/qwik-vitest/src/components/example/example.spec.tsx:12:3
    at runTest (file:///Users/riencoertjens/repos/qwik-vitest/node_modules/@vitest/runner/dist/index.js:599:11)
```

### Reproduction

https://github.com/riencoertjens/qwik-vitest

### Steps to reproduce

`npm install`
`npm vitest.ui` 

see [`./src/components/example/example.tsx`](https://github.com/riencoertjens/qwik-vitest/blob/main/src/components/example/example.tsx) for component that fails the test

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 160.98 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 115.0.5790.170
    Firefox: 115.0.3
    Safari: 16.5.2
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6 
    @builder.io/qwik-city: ^1.2.6 => 1.2.6 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.0 => 4.4.0
```

**Comment by ahnpnl** [comment]
I had the same issue too
