### ISSUE TITLE
[🐞] Unable to run SWA app that contains Auth

### ISSUE THREAD

**Issue by cwoolum** [BuilderIO/qwik#4964]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

When using Qwik auth in combination with deploying to SWA, the code rendered for the azure function doesn't have `crypto` shimmed properly. 

```
[api] [2023-08-17T23:39:26.019Z] Executing 'Functions.render' (Reason='This function was programmatically called via the host APIs.', Id=75c2ce79-3d85-4e1a-9ecf-504f24489977)
[api] [2023-08-17T23:39:26.116Z] ReferenceError: crypto is not defined
[api] [2023-08-17T23:39:26.116Z]     at hu (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:3962)
[api] [2023-08-17T23:39:26.116Z]     at Jg (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:4228)
[api] [2023-08-17T23:39:26.116Z]     at Yg (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:8444)
[api] [2023-08-17T23:39:26.116Z]     at yw (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:38691)
[api] [2023-08-17T23:39:26.116Z]     at Hi (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:42198)
[api] [2023-08-17T23:39:26.116Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[api] [2023-08-17T23:39:26.117Z]     at async Rw (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:47081)
[api] [2023-08-17T23:39:26.117Z]     at async onRequest (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:46912)
[api] [2023-08-17T23:39:26.117Z]     at async Object.ue [as next] (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/entry.azure-swa.4fbd6ac5.mjs:18:3510)
[api] [2023-08-17T23:39:26.117Z]     at async Ee (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/entry.azure-swa.4fbd6ac5.mjs:18:6488)
[api] [2023-08-17T23:39:26.223Z] Executed 'Functions.render' (Succeeded, Id=75c2ce79-3d85-4e1a-9ecf-504f24489977, Duration=228ms)
[swa] GET http://localhost:4280/api/render - 500
[swa] GET http://127.0.0.1:7071/api/render (proxy)
[api] [2023-08-17T23:39:26.556Z] Executing 'Functions.render' (Reason='This function was programmatically called via the host APIs.', Id=d13b87ca-c865-4432-9b51-ba5ae422da9c)
[api] [2023-08-17T23:39:26.566Z] ReferenceError: crypto is not defined
[api] [2023-08-17T23:39:26.566Z]     at hu (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:3962)
[api] [2023-08-17T23:39:26.567Z]     at Jg (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:4228)
[api] [2023-08-17T23:39:26.567Z]     at Yg (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:21:8444)
[api] [2023-08-17T23:39:26.567Z]     at yw (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:38691)
[api] [2023-08-17T23:39:26.567Z]     at Hi (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:42198)
[api] [2023-08-17T23:39:26.567Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[api] [2023-08-17T23:39:26.567Z]     at async Rw (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:47081)
[api] [2023-08-17T23:39:26.567Z]     at async onRequest (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/@qwik-city-plan.86282b2c.mjs:359:46912)
[swa] GET http://localhost:4280/api/render - 500
[api] [2023-08-17T23:39:26.568Z]     at async Object.ue [as next] (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/entry.azure-swa.4fbd6ac5.mjs:18:3510)
[api] [2023-08-17T23:39:26.568Z]     at async Ee (file:///C:/Users/slick/source/scratch/qwik-bug-swa/azure-functions/render/entry.azure-swa.4fbd6ac5.mjs:18:6488)
[api] [2023-08-17T23:39:26.568Z] Executed 'Functions.render' (Succeeded, Id=d13b87ca-c865-4432-9b51-ba5ae422da9c, Duration=12ms)    
[api] [2023-08-17T23:39:26.772Z] Host lock lease acquired by instance ID '000000000000000000000000FB170ED1'.
```

### Reproduction

https://github.com/cwoolum/qwik-bug-swa

### Steps to reproduce

1. Run `npm install` 
2. Run `npm run build` 
3. Run `npm serve`

### System Info

```shell
System:
    OS: Windows 10 10.0.22631
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 14.45 GB / 31.70 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.7 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 115.0.5790.111
    Edge: Spartan (44.22621.2129.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.2.7 => 1.2.7
    @builder.io/qwik-auth: 0.1.0 => 0.1.0
    @builder.io/qwik-city: ^1.2.7 => 1.2.7
    undici: 5.22.1 => 5.22.1
    vite: 4.4.7 => 4.4.7
```

**Comment by cwoolum** [comment]
Confirmed that removing `@builder.io/qwik-auth` fixes the problem

**Comment by cwoolum** [comment]
This seems to somehow have resolved itself. I'll reopen if I run into it again

**Comment by cwoolum** [comment]
Actually, I was able to recreate this again.

**Comment by cwoolum** [comment]
I confirmed that this is a problem with modular form. I was able to fix it by explicitly putting my calls inside of a `server$` wrapper.

**Comment by mhevery** [comment]
This does not seem like an issue with Qwik, rather than your runtime environment does not have the `crypto`. Qwik-auth is just a wrapper around next.js auth, and so it is next.js auth which requires `crypto`. So I think it is up to you to polyfill this.

I am going to close this issue as there is not much the core team can do about this.


I assume that SWA is [Static Web App on Azure](https://azure.github.io/static-web-apps-cli/docs/cli/swa-deploy/)?

**Comment by cwoolum** [comment]
Yes, I was referring to Azure Static web apps. I'll add more context here in case anyone else comes upon this.

Upon digging in deeper, I found out that @auth/core needs NodeJS 19 to run properly since it assumes crypto is available globally. The build system Azure uses for static web apps(Oryx) only goes up to the latest even numbered LTS so it's currently stuck on 18. Unfortunately, crypto is not available without an explicit import in that version.

The follow-up for resolution will either need to be in allowing the build system to override the NodeJS version it uses or to shim crypto so it's available globally.

If I find a solution, I'll tag this ticket.
