### ISSUE TITLE
Tutorial Running Code not Supported by Version Used[🐞]

### ISSUE THREAD

**Issue by dillonmarquard** [BuilderIO/qwik#5094]
### Which component is affected?

Qwik Runtime

### Describe the bug

In the tutorial here: https://qwik.builder.io/tutorial/composing/dollar/
Using the solution code, the update to the counter and delay do not occur in the tutorial side-by-side render when clicking the button.
Opening the solution code in the playground uses qwik version 1.1.5, but this does code not appear to work until version 1.2.0.
I suspect that the tutorial side-by-side render is also using an unsupported version before 1.2.0.
I am unsure how a version is selected to run the tutorial demo, thus I will defer this bug to more apt contributors.

### Reproduction

https://qwik.builder.io/tutorial/composing/dollar/

### Steps to reproduce

Simply running the tutorial, clicking "Show me" to load the solution code and clicking the button should suffice to reproduce the bug.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 92.99 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5
```

### Additional Information

Opening the solution code in the playground uses qwik version 1.1.5, but this does code not appear to update the counter as-intended until version 1.2.0.
I suspect that the tutorial side-by-side render is also using an unsupported version before 1.2.0.

**Comment by mhevery** [comment]
The workspace has been pinned to v1.1.5 because there is an issue with Rollup in v1.2.0
```
Error: Could not load /app_component_ncbm0trxwgc.js (imported by app.tsx): Cannot access the file system (via "fs.readFile") when using the browser build of Rollup. Make sure you supply a plugin with custom resolveId and load hooks to Rollup. at fe (eval at g (http://localhost:3000/repl/repl-sw.js:1:341), <anonymous>:12:23466) at Object.eval [as readFile] (eval at g (http://localhost:3000/repl/repl-sw.js:1:341), <anonymous>:12:353107) at eval (eval at g (http://localhost:3000/repl/repl-sw.js:1:341), <anonymous>:12:359412) at async ul.work (eval at g (http://localhost:3000/repl/repl-sw.js:1:341), <anonymous>:12:353044)
```

We are aware of this issue, unfortunately it is stuck behind other priority items.
