### ISSUE TITLE
[📖] How to avoid server only code to be shipped in the client bundle

### ISSUE THREAD

**Issue by juanpmarin** [BuilderIO/qwik#5160]
### Suggestion

Hi! I recently detect that some code that should not be in my client bundle, is there. I tried to find some guidance on how to avoid that, remix, for example, have a very good document on the subject: https://remix.run/docs/en/1.19.3/guides/constraints#server-code-pruning

Is there something similar for qwik that I could not find?
Is there something similar to .server.ts files in remix for qwik?

**Comment by mhevery** [comment]
That is a very generic question. Can you provide an example of what happened?

**Comment by juanpmarin** [comment]
Although it is a generic question, it would be great to have documentation on it, similar to the document that remix has.

In my specific case, this is what I found:

We don't use qwik to connect to our database directly, but instead we have services that we call using gRPC and https://connectrpc.com/

We're also using qwik server side apis like sharedMap to share some context from layouts to specific routes, modular-forms is also being used to handle our form logic.

I was checking the code generated in the `dist/builder` folder:

This is one of our `formAction$`:
```
export const usePostNewQuote = formAction$<RecipientForm>(
  async (recipient, { redirect, platform, sharedMap, request, env }) => {
    const draftsRepository = DraftsRepository.fromPlatform(platform);
    const tracker = DefaultAnalyticsTracker.fromEnv(env);

    const draft = sharedMap.get("draft") as Draft;
    const quote = sharedMap.get("quote") as Quote;
    const user = sharedMap.get("user") as User;

    const requiresDocument = checkRequiresDocument(draft.courier);

    if (requiresDocument && !recipient.document) {
      throw new FormError<RecipientForm>("Document is required", {
        document: "required",
      });
    }

    if (requiresDocument && !recipient.documentType) {
      throw new FormError<RecipientForm>("Document type is required", {
        documentType: "required",
      });
    }

    await draftsRepository.save({
      ...draft,
      recipient: {
        ...recipient,
        document: recipient.document || "",
        documentType: recipient.documentType || "",
      },
    });

    await tracker.track(
      "Shipping - Quote recipient set",
      {
        quote: quote.name,
      },
      {
        user: user.name,
        request,
      },
    );

    throw redirect(302, `../summary`);
  },
  zodForm$(RecipientSchema),
);
```

and I found that piece of code in the client bundle, in this path `dist/build/q-78c6dbe1.js`:
```
  W = async (
    e,
    { redirect: p, platform: n, sharedMap: o, request: r, env: d },
  ) => {
    const i = S.fromPlatform(n),
      t = g.fromEnv(d),
      s = o.get("draft"),
      a = o.get("quote"),
      c = o.get("user"),
      m = w(s.courier);
    throw m && !e.document
      ? new h("Document is required", { document: "required" })
      : m && !e.documentType
      ? new h("Document type is required", { documentType: "required" })
      : (await i.save({
          ...s,
          recipient: {
            ...e,
            document: e.document || "",
            documentType: e.documentType || "",
          },
        }),
        await t.track(
          "Shipping - Quote recipient set",
          { quote: a.name },
          { user: c.name, request: r },
        ),
        p(302, "../summary"));
  };
  ```
  
  I also found blocks like this in the `q-manifest.json`, but grpc and connect are only being used server side:
  
![image](https://github.com/BuilderIO/qwik/assets/13415603/6f955d78-50cb-400e-a697-260cdf9b541b)

**Comment by gioboa** [comment]
Can you create a minimal repo to investigate in this issue please? 🙏

**Comment by juanpmarin** [comment]
@gioboa sure!
Here it is: https://github.com/juanpmarin/qwik-issues-repro

Repro steps:
- Run `npm run build`
- Look for "THIS IS SERVER ONLY CODE" in `dist/build` files


In my case, I found the server code in `dist/build/q-335eafed.js`:
```
import { HelloSchema as t } from "./q-7498aa87.js";
import "./q-225dcdfb.js";
import "./q-a4f8d898.js";
import "./q-f55dd5f2.js";
const m = t,
  p = (o, { redirect: s }) => {
    throw (
      (console.log("VALUES", o),
      console.log("THIS IS SERVER ONLY CODE"),
      s(302, "/success"))
    );
  };
export { p as s_AA5LgweUUMM, m as s_yvfvwzPD6Bs };
```

**Comment by gioboa** [comment]
I will look at this. 👍

**Comment by fabian-hiller** [comment]
@gioboa what do you think needs to be changed to prevent this from happening? `formAction$` builds on `globalActionQrl`. https://github.com/fabian-hiller/modular-forms/blob/v0.20.2-qwik/packages/qwik/src/actions/formAction%24.ts#L68

**Comment by maiieul** [comment]
@fabian-hiller might be because there is no `/*#__PURE__*/ ` before `implicit$FirstArg(formActionQrl)`?

**Comment by fabian-hiller** [comment]
Yes, maybe that's the reason. Can @mhevery or @manucorporat confirm this? If so, I'll try to publish an update in the evening.

**Comment by gioboa** [comment]
I manually added `/* @__PURE__ */` in the library but this doesn't solve the problem
<img width="1249" alt="Screenshot 2023-09-26 at 18 35 33" src="https://github.com/BuilderIO/qwik/assets/35845425/39b52f8a-6642-4390-ac4d-ffa5c14cb3c2">

**Comment by mhevery** [comment]
So, the optimizer treats certain functions as special: https://github.com/BuilderIO/qwik/blob/7e85de911654ec03b911e128d9148931b2fcf661/packages/qwik/src/optimizer/src/plugins/plugin.ts#L36-L45C1

As of right now, that list is hard-coded. If I add `formAction$` to the list, everything works as expected.

I think the solution here is to make that list configurable, and the question would be how to configure it:

1. We could pass it as option to `qwikVite()` in `vite.config.ts`
2. But I think a better solution would be for the plugin to somehow read the `package.json` of the third-party library and get that list from there.  

--- 


But a bigger question is, does this cause problems? Even though it makes it to the client bundle, it should never be loaded. (Or is the issue that sometimes it is loaded as a side-effect?)

**Comment by fabian-hiller** [comment]
Yes, as an author I also prefer the second option with the `package.json`. I think some people want to hide the server-side implementation, and it also reduces network traffic if that code is not loaded at all.

**Comment by juanpmarin** [comment]
@mhevery I think it does cause problems, I see it as a security risk, details about internal infrastructure, database schema, secrets could be filtered and be used to attack

**Comment by juanpmarin** [comment]
@mhevery @gioboa what about a naming convention for the optimizer  to find server side functions? Like functions ending in `action$`

**Comment by mhevery** [comment]
> @mhevery I think it does cause problems, I see it as a security risk, details about internal infrastructure, database schema, secrets could be filtered and be used to attack

not sure I understand this...

**Comment by mhevery** [comment]
> @mhevery @gioboa what about a naming convention for the optimizer to find server side functions? Like functions ending in `action$`

Yes, but then the developer will have to see the extra name like `server`.

**Comment by fabian-hiller** [comment]
I could imagine it. However, I find little time at the moment and it could take a while. Therefore it might be better if someone else creates a PR with a first draft and I review it.

**Comment by wmertens** [comment]
But guarding code with `if (is server)` will work no matter what, right?

**Comment by adamayres** [comment]
I recently ran into this problem when migrating some existing forms that used `routeAction$` and `globalAction$` to use `formAction$` in the Modular Form lib.

> But a bigger question is, does this cause problems? Even though it makes it to the client bundle, it should never be loaded. (Or is the issue that sometimes it is loaded as a side-effect?)

In my specific case I had two `formAction$`'s, one that registers a user and one that logins in a user that use Drizzle, Postgres, Lucia, and Oslo. When attempting to build I run into two classes of issues:

1.) Warnings from Vite that there are modules being included in a client bundle that have been externalized.

```
[plugin:vite:resolve] [plugin vite:resolve] Module "os" has been externalized for browser compatibility, imported by "/Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/postgres@3.4.4/node_modules/postgres/src/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

2.) An error during the build that fails the build. I assume in this case it is failing on browserifying the crypto module.

```
error during build:
RollupError: Unexpected character '�'
    at getRollupError (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/parseAst.js:376:41)
    at ParseError.initialise (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:11158:28)
    at convertNode (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:12898:10)
    at convertProgram (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:12218:12)
    at Module.setSource (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:14042:24)
    at async ModuleLoader.addModuleSource (file:///Users/adam.ayres/dev/buttaplz/node_modules/.pnpm/rollup@4.13.0/node_modules/rollup/dist/es/shared/node-entry.js:18681:13)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed.
```

> But guarding code with `if (isServer)` will work no matter what, right?

If I guard my the callback in my `formAction$` with a `if (isServer)` check then it prevents this issue.

**Comment by fabian-hiller** [comment]
@wmertens I would also be interested in creating a PR to fix this issue. Should I proceed with the `package.json` solution?

**Comment by wmertens** [comment]
@fabian-hiller I think that's a really complex solution with many edge cases. I don't even like the current approach very much.

It is much simpler and more modular to use `if (isServer)` in the library code, and making sure that the optimizer is smart about ignoring empty functions. For that latter, it should convert any qrl function with an empty body into a noopQrl.

**Comment by fabian-hiller** [comment]
So how should I proceed? I tested `if (isServer)` in Modular Forms but as far as I can remember it did not work because the optimizer probably treats the already bundled library code differently. Did the optimizier change? Should I test it again?

**Comment by wmertens** [comment]
@fabian-hiller yes, you should use `if (isServer)` and make sure that the build externalizes `@builder.io/qwik/build`. This should already be the case. You can check by searching for isServer in the build

**Comment by fabian-hiller** [comment]
I will probably try this out next week.

**Comment by fabian-hiller** [comment]
@wmertens it still does not work. I basically wrapped our custom logic in the first argument of `globalActionQrl` in [`formActionQrl`](https://github.com/fabian-hiller/modular-forms/blob/main/packages/qwik/src/actions/formAction%24.ts#L74-L161) in `isServer`. I made sure that `@builder.io/qwik/build` is externalized. It seems that the optimizer ignores the `isServer` in the `index.qwik.mjs` files.

**Comment by wmertens** [comment]
Can you paste a snippet of what it makes?

**Comment by fabian-hiller** [comment]
A snipped of the build output or the `index.qwik.mjs` file?

**Comment by wmertens** [comment]
Both :)

**Comment by fabian-hiller** [comment]
### Library

formAction$.ts

```ts
export function formActionQrl<
  TFieldValues extends FieldValues,
  TResponseData extends ResponseData = undefined,
>(
  action: QRL<FormActionFunction<TFieldValues, TResponseData>>,
  arg2: FormActionArg2<TFieldValues>
): Action<
  FormActionStore<TFieldValues, TResponseData>,
  PartialValues<TFieldValues>,
  true
> {
  return globalActionQrl(
    $(
      async (
        jsonData: unknown,
        event: RequestEventAction
      ): Promise<FormActionStore<TFieldValues, TResponseData>> => {
        if (isServer) {
          // More code here...
        }
        return {} as never;
      }
    ),
    {
      id: action.getHash(),
    }
  );
}
```

index.qwik.mjs

```ts
function formActionQrl(action, arg2) {
  return globalActionQrl(/* @__PURE__ */ inlinedQrl(async (jsonData, event) => {
    const [action2, arg22] = useLexicalScope();
    if (isServer) {
      // More code here ...
    }
    return {};
  }, "formActionQrl_globalActionQrl_VOLgKQUpNuc", [
    action,
    arg2
  ]), {
    id: action.getHash()
  });
}
```

### Website

login/index.tsx

```ts
export const useFormAction = formAction$<LoginForm>((values) => {
  console.log('SHOULD RUN ON SERVER ONLY');
}, valiForm$(LoginSchema));
```

build/q-Cv8IuI2D.js

```ts
import{L as o}from"./q-CP0CFkJm.js";import"./q-IxejFPpX.js";import"./q-6aI8-geF.js";import"./q-23zXvFSW.js";import"./q-fidbyLog.js";import"./q-BhcrKidH.js";const t=()=>{console.log("SHOULD RUN ON SERVER ONLY")},p=Object.freeze(Object.defineProperty({__proto__:null,s_8ZD0uaqWLo0:t},Symbol.toStringTag,{value:"Module"})),c=o;export{p as a,c as s,t as s_8ZD0uaqWLo0};

```

**Comment by wmertens** [comment]
Ah ok, that's a configuration issue, formAction$ must be marked as server only by qwik-city. In the meantime you can put isServer guards in the client code, which is more correct IMHO but also a little annoying.

**Comment by wmertens** [comment]
Oh I didn't notice it was imported from modular forms.

So two options: pass the name into the optimizer as server only or always use guards. 

The first could be done in the config or via a plugin.

The second is always manual

**Comment by fabian-hiller** [comment]
> The first could be done in the config or via a plugin.

Is this already possible without changing Qwik or Qwik City?
