### ISSUE TITLE
[🐞] Can't run local development server with Docker

### ISSUE THREAD

**Issue by zoltanszogyenyi** [BuilderIO/qwik#5218]
### Which component is affected?

Qwik Runtime

### Describe the bug

There's an issue when using Docker and Dev Containers from VS Code:

```
197.0   Downloaded bzip2-sys v0.1.11+1.0.8
197.3   Downloaded ring v0.16.20
197.5 error: failed to compile `wasm-pack v0.12.1`, intermediate artifacts can be found at `/tmp/cargo-install7ENTWT`
197.5 
197.5 Caused by:
197.5   package `clap_builder v4.4.5` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.66.0-nightly
[2023-09-26T09:22:12.141Z] 
197.5   Try re-running cargo install with `--locked`
197.5      Summary Successfully installed cargo-insta! Failed to install wasm-pack (see error(s) above).
197.5 error: some crates failed to install
------
[2023-09-26T09:22:12.141Z] Dockerfile-with-features:5
--------------------
   4 |     
   5 | >>> RUN rustup toolchain install nightly-2022-09-23; \
   6 | >>>     rustup default nightly-2022-09-23; \
   7 | >>>     rustup --version; \
   8 | >>>     cargo --version; \
   9 | >>>     rustc --version; \
  10 | >>>     rustup update; \
  11 | >>>     rustup target add wasm32-unknown-unknown; \
  12 | >>>     cargo install cargo-insta wasm-pack; \
  13 | >>>     rustup component add clippy; \
  14 | >>>     corepack enable --install-directory ~/bin
  15 |     
--------------------
ERROR: failed to solve: process "/bin/bash -exo pipefail -c rustup toolchain install nightly-2022-09-23;     rustup default nightly-2022-09-23;     rustup --version;     cargo --version;     rustc --version;     rustup update;     rustup target add wasm32-unknown-unknown;     cargo install cargo-insta wasm-pack;     rustup component add clippy;     corepack enable --install-directory ~/bin" did not complete successfully: exit code: 101
[2023-09-26T09:22:12.147Z] Stop (198855 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/rh/zhyxfc3965sb3l3j3nz_7nd00000gn/T/devcontainercli/container-features/0.51.1-1695719933284/Dockerfile-with-features -t vsc-qwik-e04d632de92396249c34a8447e8758f8f02685b548cc76593d2e475d76c06ab2 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer
[2023-09-26T09:22:12.147Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /var/folders/rh/zhyxfc3965sb3l3j3nz_7nd00000gn/T/devcontainercli/container-features/0.51.1-1695719933284/Dockerfile-with-features -t vsc-qwik-e04d632de92396249c34a8447e8758f8f02685b548cc76593d2e475d76c06ab2 --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer
[2023-09-26T09:22:12.147Z]     at CAA (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:463:1752)
[2023-09-26T09:22:12.148Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-09-26T09:22:12.148Z]     at async jw (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:1691)
[2023-09-26T09:22:12.148Z]     at async FK (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:462:610)
[2023-09-26T09:22:12.148Z]     at async FAA (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-09-26T09:22:12.148Z]     at async GC (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-09-26T09:22:12.148Z]     at async VeA (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:12240)
[2023-09-26T09:22:12.148Z]     at async WeA (/Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:11981)
[2023-09-26T09:22:12.153Z] Stop (202202 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/zoltanszogyenyi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-4ff0a76a-8de1-45fb-9218-e523ffd920941695719928828 --workspace-folder /Users/zoltanszogyenyi/Projects/bergside/qwik --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/zoltanszogyenyi/Projects/bergside/qwik --id-label devcontainer.config_file=/Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-09-26T09:22:12.153Z] Exit code 1
[2023-09-26T09:22:12.156Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/zoltanszogyenyi/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/zoltanszogyenyi/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-4ff0a76a-8de1-45fb-9218-e523ffd920941695719928828 --workspace-folder /Users/zoltanszogyenyi/Projects/bergside/qwik --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/zoltanszogyenyi/Projects/bergside/qwik --id-label devcontainer.config_file=/Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/zoltanszogyenyi/Projects/bergside/qwik/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-09-26T09:22:12.156Z] Exit code 1
```

Because of this I am unable to run Qwik locally on my machine to contribute.

### Reproduction

https://github.com/zoltanszogyenyi/qwik

### Steps to reproduce

Run Dev Containers with VS Code and Docker already running in the background.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 25.77 GB / 72.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Firefox: 115.0.2
    Safari: 16.5.2
```

**Comment by mhevery** [comment]
> Run Dev Containers with VS Code and Docker already running in the background.

Sorry, I am not familiar with Docker. Could I have more detailed instructions on how to reproduce the error. The above is insufficient for me..

**Comment by zoltanszogyenyi** [comment]
Hey @mhevery,

Thanks for stepping in! I'm also not that familiar with Docker, hence why I'm having trouble using and debugging it.

The reason I'm using Docker is because it's recommended by the contribution guide: https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md

Is there any other way I can set up the Qwik docs locally so that I can create the Flowbite Quickstart documentation?

Cheers,
Zoltan

**Comment by SauravChanda** [comment]
Hi @mhevery @zoltanszogyenyi I am also stuck at this point. I am familiar with Docker and trying to solve it, will raise a PR once done. 

Also maybe the issue is that we are trying to use a nightly version of Rust, not sure why is that. Will update to LTS.

**Comment by SauravChanda** [comment]
Hi @zoltanszogyenyi @mhevery, I have raised a PR for this issue #5237 . Feel free to test it out, should resolve the issue.
