### ISSUE TITLE
[🐞]TypeError: fetch failed thrown by @builder.io/qwik/optimizer.cjs

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#5477]
### Which component is affected?

Qwik Runtime

### Describe the bug

After updating to v.1.2.13, I keep getting the following errors in local dev:
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getInfoForSrc (/Users/yasser/projects/starrymaps-qwik/node_modules/@builder.io/qwik/optimizer.cjs:2483:19)
    at async /Users/yasser/projects/starrymaps-qwik/node_modules/@builder.io/qwik/optimizer.cjs:2515:22 {
  cause: Error: connect ECONNREFUSED ::1:5173
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 5173
  }
}
```

The images Im loading are displayed without issues on the page. So they do exist, yet the fetch fails.
I recently installed node-fetch and uninstalled it and do not use it anymore. Could this be causing some sort of conflicts?

The root of this seems to be the following bit
```
 async function _getInfo(originalSrc) {
      if (originalSrc.startsWith('blob:')) {
        return undefined;
      }
      const url = new URL('/__image_info', location.href);
      url.searchParams.set('url', originalSrc);
      // =====>> The line below is where the exception is raised
      const res = await fetch(url);
      if (res.ok) {
        return await res.json();
      } else {
        return undefined;
      }
    }
```

It seems like the above belongs to imageTools which shows tips on improving images in dev.
![Screenshot 2023-11-24 at 11 46 20 a m](https://github.com/BuilderIO/qwik/assets/2945770/1b91e1a5-daa2-48b5-97f7-5feb39fe98c0)

### Reproduction

I can't reproduce this since I only see it in local dev for now

### Steps to reproduce

- in routes/index.tsx
```typescript
import exampleImage from '~/media/images/an-example.webp?jsx';

export default component$(() => {
return (<exampleImage alt="An example" />);
});
```
The above is enough to produce the errors I see locally

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (12) x64 Apple M2 Pro
    Memory: 33.75 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
    pnpm: 7.9.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.3
  npmPackages:
    @builder.io/partytown: ^0.8.0 => 0.8.1 
    @builder.io/qwik: ^1.2.13 => 1.2.18 
    @builder.io/qwik-city: ^1.2.13 => 1.2.18 
    undici: ^5.22.1 => 5.27.2 
    vite: ^4.4.0 => 4.5.0
```

**Comment by mhevery** [comment]
Closing for now, as I  believe this has been fixed, and need a reproduction.

**Comment by genki** [comment]
I have met this issue but solved after updating qwik and clearing browser cache :)
