### ISSUE TITLE
[BUG] Dev SSR script fails in Qwik City Starter

### ISSUE THREAD

**Issue by nnelgxorz** [BuilderIO/qwik#551]
### Qwik Version

0.0.21

### Operating System (or Browser)

Linux

### Node Version (if applicable)

v16.3.0

### Which component is affected?

Starters / CLI

### Expected Behaviour

`npm run dev.ssr` runs the dev server in ssr mode.

### Actual Behaviour

The script fails with the following stack trace:

```
8:37:13 PM [vite] Internal server error: Duplicate implementations of "JSXNodeImpl" found
      at isJSXNode (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2394:19)
      at processNode (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2364:9)
      at processNode (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2369:20)
      at new JSXNodeImpl (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2348:30)
      at Module.jsx (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2335:12)
      at JSXNodeImpl.Root [as type] (/src/root.tsx:11:26)
      at processNode (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:2369:37)
      at Module.render (../../../dist-dev/tsc-out/packages/qwik/src/core/util/qdev.js:4496:37)
      at Module.renderToString (/node_modules/@builder.io/qwik/server.mjs?v=d4420e18:12217:8)
      at async ../node_modules/@builder.io/qwik/optimizer.cjs:1675:30
```

### Additional Information

Used the Qwik City starter, Netlify server adapter and Prettier, Eslint, Tailwindcss. I haven't checked any other combinations.

**Comment by manucorporat** [comment]
looking at this issue now!

**Comment by nnelgxorz** [comment]
Fixed in latest
