### ISSUE TITLE
[🐞] qwik.new error: Input file contains unsupported image format

### ISSUE THREAD

**Issue by yasserlens** [BuilderIO/qwik#5564]
### Which component is affected?

Qwik Runtime

### Describe the bug

The stackblitz qwik.new instance throws an error on startup: Input file contains unsupported image format
```
Input file contains unsupported image format
Stack trace
 at _napi_create_error (/home/projects/qwik-starter/node_modules/sharp/build/Release/sharp-emscripten-wasm32.node.js:5768:14)
    at <anonymous> (Napi)
    at invoke_viii (/home/projects/qwik-starter/node_modules/sharp/build/Release/sharp-emscripten-wasm32.node.js:7836:27)
    at <anonymous> (MetadataWorker)
    at <anonymous> (Napi)
    at invoke_ii (/home/projects/qwik-starter/node_modules/sharp/build/Release/sharp-emscripten-wasm32.node.js:7880:34)
    at <anonymous> (Napi)
    at <anonymous> (Napi)
    at eval (/home/projects/qwik-starter/node_modules/sharp/build/Release/sharp-emscripten-wasm32.node.js:4589:31
```

There is no indication on what the file in question was.

### Reproduction

qwik.new as of 11 Dec 2023

### Steps to reproduce

- Go to qwik.new
- Wait for the environment to load
- Error will be once env is loaded

### System Info

```shell
NA - it's on qwik.new
```

**Comment by wmertens** [comment]
I cannot reproduce this :-( By default it starts with 1.2.11 and that works, when I upgrade to 1.3.0 it still works

**Comment by yasserlens** [comment]
I can confirm that this is now resolved. Thanks
