### ISSUE TITLE
[🐞] Can't deploy to cloudflare pages

### ISSUE THREAD

**Issue by n3oney** [BuilderIO/qwik#5727]
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I'm trying to deploy a simple project to Cloudflare Pages, and I'm getting this error:

```
00:57:57.551 | $ tsc --incremental --noEmit --pretty
-- | --
00:57:57.560 | $ vite build
00:57:58.024 | failed to load config from /opt/buildhome/repo/vite.config.ts
00:57:58.024 | error during build:
00:57:58.025 | ReferenceError: ReadableStream is not defined
00:57:58.025 | at Object.<anonymous> (/opt/buildhome/repo/node_modules/undici/lib/fetch/response.js:506:3)
00:57:58.026 | at Module._compile (node:internal/modules/cjs/loader:1198:14)
00:57:58.026 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
00:57:58.026 | at Module.load (node:internal/modules/cjs/loader:1076:32)
00:57:58.026 | at Function.Module._load (node:internal/modules/cjs/loader:911:12)
00:57:58.027 | at Module.require (node:internal/modules/cjs/loader:1100:19)
00:57:58.027 | at require (node:internal/modules/cjs/helpers:119:18)
00:57:58.027 | at Object.<anonymous> (/opt/buildhome/repo/node_modules/undici/index.js:122:27)
00:57:58.027 | at Module._compile (node:internal/modules/cjs/loader:1198:14)
00:57:58.027 | at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
00:57:58.031 | error: script "build.client" exited with code 1 (SIGHUP)
00:57:58.038 | error: script "build" exited with code 1 (SIGHUP)
00:58:00.189 | Finished
00:58:00.190 | Note: No functions dir at /functions found. Skipping.
00:58:00.190 | Validating asset output directory
00:58:00.190 | Error: Output directory "dist" not found.
00:58:01.102 | Failed: build output directory not found
```

### Reproduction

N/A

### Steps to reproduce

```
bun create qwik@latest
# use the template with no examples, just a raw empty setup
qwik add cloudflare-pages
```

then push it to GitHub and try to deploy on Cloudflare Pages

### System Info

```shell
Cloudflare Pages, build system version 2
```

**Comment by n3oney** [comment]
I've tried once more to create the project but now I've used `bun create cloudflare@latest` instead of `bun create qwik@latest` and it seems to have worked...? I managed to deploy it. Trying to find the differences now.

**Comment by n3oney** [comment]
I literally can't find a difference. Oh well. I guess I'll close this.

**Comment by PatrickJS** [comment]
yeah looks like an issue with Bun missing ReadableStream. right now the only fully supported runtime for building is Node.js but after it's built it can run in any runtime

**Comment by n3oney** [comment]
Actually, I still had an issue with this. The solution was to `npm i -D undici@5.22.0`

**Comment by Croissong** [comment]
I fixed it by updating the node version in `package.json` & `.node-version` to 21
