### ISSUE TITLE
[🐞] npm ERR! code EUNSUPPORTEDPROTOCOL

### ISSUE THREAD

**Issue by alexismch** [BuilderIO/qwik#5803]
### Which component is affected?

Qwik Runtime

### Describe the bug

Hi!

While trying to install Qwik Labs, an npm error occurs.

Here is the full report : 
```log
0 verbose cli /Users/{user}/.nvm/versions/node/v18.18.2/bin/node /Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.4.0
2 info using node@v18.18.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/{user}/.npm/_cacache/tmp/git-clonejbTBH8/.npmrc Completed in 0ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/{user}/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/{user}/.nvm/versions/node/v18.18.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install
22 verbose argv "install" "--force" "--cache" "/Users/{user}/.npm" "--prefer-offline" "false" "--prefer-online" "false" "--offline" "false" "--no-progress" "--no-save" "--no-audit" "--include" "dev" "--include" "peer" "--include" "optional" "--no-package-lock-only" "--no-dry-run"
23 timing npm:load:setTitle Completed in 6ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/Users/{user}/.npm/_logs/2024-01-31T14_22_57_079Z-
26 verbose logfile /Users/{user}/.npm/_logs/2024-01-31T14_22_57_079Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 warn using --force Recommended protections disabled.
31 timing npm:load Completed in 21ms
32 timing arborist:ctor Completed in 0ms
33 silly logfile start cleaning logs, removing 1 files
34 silly logfile done cleaning log files
35 timing arborist:ctor Completed in 0ms
36 timing idealTree:init Completed in 6ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 timing idealTree Completed in 7ms
40 timing command:install Completed in 9ms
41 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
41 verbose stack     at unsupportedURLType (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:310:15)
41 verbose stack     at fromURL (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:367:13)
41 verbose stack     at Function.resolve (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:83:12)
41 verbose stack     at #nodeFromEdge (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1070:22)
41 verbose stack     at #buildDepStep (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:939:35)
41 verbose stack     at #buildDeps (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:791:30)
41 verbose stack     at Arborist.buildIdealTree (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:218:28)
41 verbose stack     at async Promise.all (index 1)
41 verbose stack     at async Arborist.reify (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:160:5)
41 verbose stack     at async Install.exec (/Users/{user}/.nvm/versions/node/v18.18.2/lib/node_modules/npm/lib/commands/install.js:153:5)
42 verbose cwd /Users/{user}/.npm/_cacache/tmp/git-clonejbTBH8
43 verbose Darwin 23.1.0
44 verbose node v18.18.2
45 verbose npm  v10.4.0
46 error code EUNSUPPORTEDPROTOCOL
47 error Unsupported URL Type "workspace:": workspace:*
48 verbose exit 1
49 timing npm Completed in 90ms
50 verbose unfinished npm timer reify 1706710977159
51 verbose unfinished npm timer reify:loadTrees 1706710977160
52 verbose unfinished npm timer idealTree:buildDeps 1706710977167
53 verbose unfinished npm timer idealTree:#root 1706710977167
54 verbose code 1
55 error A complete log of this run can be found in: /Users/{user}/.npm/_logs/2024-01-31T14_22_57_079Z-debug-0.log
```

### Reproduction

https://qwik.dev/docs/labs/#installation

### Steps to reproduce

`npm install github:BuilderIo/qwik-labs-build#main`

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (12) arm64 Apple M3 Pro
    Memory: 1.51 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    Yarn: 1.22.21 - ~/Documents/rosa/node_modules/.bin/yarn
    npm: 10.2.3 - ~/Documents/rosa/node_modules/.bin/npm
    pnpm: 8.14.3 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.85
    Safari: 17.1.2
  npmPackages:
    @builder.io/angular: 2.2.1 => 2.2.1 
    @builder.io/qwik: 1.3.2 => 1.3.2 
    @builder.io/qwik-city: 1.3.2 => 1.3.2 
    @builder.io/sdk-qwik: 0.7.1-0 => 0.7.1-0 
    vite: 5.0.11 => 5.0.11
```

### Additional Information

I guess that the commit introducing the error is : https://github.com/BuilderIO/qwik-labs-build/commit/a8b03fc6adaf19c4b8f698ee92da6d6e64a70524

**Comment by alexismch** [comment]
The linked commit seems accurate. I successfully installed with the previous hash.
`github:BuilderIo/qwik-labs-build#36582dc0503bf665daff9686d2a27d742145795d`

**Comment by wmertens** [comment]
Right that's probably because that doesn't get released like the other packages. The easiest fix is to run `syncpack` before publishing but not committing the result. We need a script that does that, also for qwik-react.

**Comment by mhevery** [comment]
ohh. yes, any chance that @wmertens can take on it?

**Comment by mhevery** [comment]
alternatively we could just go back to the old system here. (basically revert it just for that directory)

**Comment by brandonpittman** [comment]
Yeah, I wiped my node_modules and now this won't install and can't deploy.

**Comment by brandonpittman** [comment]
> The linked commit seems accurate. I successfully installed with the previous hash. `npm i github:BuilderIo/qwik-labs-build#36582dc0503bf665daff9686d2a27d742145795d`

Thanks for this tip.

**Comment by brandonpittman** [comment]
Should the docs have a message about this in the meantime? Anyone trying it for the first time will be frustrated.

**Comment by alexismch** [comment]
> Should the docs have a message about this in the meantime? Anyone trying it for the first time will be frustrated.

Thanks to your suggestion, I've opened a PR for that : https://github.com/BuilderIO/qwik/pull/5858
