### ISSUE TITLE
[🐞] fresh qwikcity throw error

### ISSUE THREAD

**Issue by mhamri** [BuilderIO/qwik#5805]
### Which component is affected?

Starters / CLI

### Describe the bug

I'm new to qwik and trying to learn, so just following the qwick document and faced difficutly creating the base app to run. here is commands that I run 

two issues : pnpm install is failing and pnpm start is failing

### Reproduction

-

### Steps to reproduce

```shell

PS E:\hustling\toDelete\qwik-learn> pnpm create qwik@latest

      ............
    .::: :--------:.
   .::::  .:-------:.
  .:::::.   .:-------.
  ::::::.     .:------.
 ::::::.        :-----:
 ::::::.       .:-----.
  :::::::.     .-----.
   ::::::::..   ---:.
    .:::::::::. :-:.
     ..::::::::::::
             ...::::


T  Let's create a  Qwik App  ✨ (v1.4.3)
|
o  Where would you like to create your new project? (Use '.' or './' for current directory)
|  ./qwik-learn
|
•  Creating new project in  E:\hustling\toDelete\qwik-learn  ... 🐇
|
o  Select a starter
|  Basic App (Qwik City + Qwik)
|
o  Would you like to install pnpm dependencies?
|  Yes
|
o  Initialize a new git repository?
|  Yes
|
o  Finishing the install. Wanna hear a joke?
|  Yes
|
o  🙈 ---------------------------------------------------------------------+
|                                                                          |
|  I've got a great joke about construction, but I'm still working on it.  |
|                                                                          |
|                                                                          |
+--------------------------------------------------------------------------+
|
o  App Created 🐰
|
o  Git initialized 🎲
|
|
x  EXDEV: cross-device link not permitted, rename 'C:\Users\me\AppData\Local\Temp\create-qwik-2b1enkyxiib\node_modules' -> 'E:\hustling\toDelete\qwik-learn\node_modules'
|
|
|
x   pnpm install failed
|   You might need to run "pnpm install" manually inside the root of the project.
|
|
o  Failed to install pnpm dependencies 📋
|
o  Result ------------------------------------------------+
|                                                         |
|  🦄  Success!  Project created in qwik-learn directory  |
|                                                         |
|  🤍 Integrations? Add Netlify, Cloudflare, Tailwind...  |
|     pnpm qwik add                                       |
|                                                         |
|  📄 Relevant docs:                                      |
|     https://qwik.builder.io/docs/getting-started/       |
|                                                         |
|  💬 Questions? Start the conversation at:               |
|     https://qwik.builder.io/chat                        |
|     https://twitter.com/QwikDev                         |
|                                                         |
|  👀 Presentations, Podcasts and Videos:                 |
|     https://qwik.builder.io/media/                      |
|                                                         |
|  🐰 Next steps:                                         |
|     cd qwik-learn                                       |
|     pnpm install                                        |
|     pnpm start                                          |
|                                                         |
|                                                         |
+---------------------------------------------------------+
|
—  Happy coding! 🎉

PS E:\hustling\toDelete> cd .\qwik-learn\
PS E:\hustling\toDelete\qwik-learn> pnpm i
Packages: +352
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 408, reused 354, downloaded 0, added 352, done

devDependencies:
+ @builder.io/qwik 1.4.3
+ @builder.io/qwik-city 1.4.3
+ @types/eslint 8.56.2
+ @types/node 20.11.13
+ @typescript-eslint/eslint-plugin 6.20.0
+ @typescript-eslint/parser 6.20.0
+ eslint 8.56.0
+ eslint-plugin-qwik 1.4.3
+ prettier 3.2.4
+ typescript 5.3.3
+ undici 6.5.0
+ vite 5.0.12
+ vite-tsconfig-paths 4.3.1

Done in 9.3s
PS E:\hustling\toDelete\qwik-learn> pnpm start

> my-qwik-basic-starter@ start E:\hustling\toDelete\qwik-learn
> vite --open --mode ssr

failed to load config from E:\hustling\toDelete\qwik-learn\vite.config.ts
error when starting dev server:
ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (E:\hustling\toDelete\qwik-learn\node_modules\.pnpm\undici@6.5.0\node_modules\undici\lib\fetch\response.js:516:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (E:\hustling\toDelete\qwik-learn\node_modules\.pnpm\undici@6.5.0\node_modules\undici\lib\fetch\index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

```

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 7940HS w/ Radeon 780M Graphics
    Memory: 1.40 GB / 15.21 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.4.3 => 1.4.3
    @builder.io/qwik-city: ^1.4.3 => 1.4.3
    undici: * => 6.5.0
    vite: ^5.0.12 => 5.0.12
```

**Comment by PatrickJS** [comment]
you need to run `dev`.  when you run `start` it's assuming the `build.client` is built already. @wmertens where is the place to create a better error for this in the cli?

**Comment by wmertens** [comment]
No, the node version needs to be 18 but better 20.

Pnpm start should work

**Comment by mhamri** [comment]
update to node 20 solved the issue. 

btw these need an update. additionally need adding instruction to add sharp in pnpm( `pnpm add sharp` ). node 20 isn't solely enough. 
![image](https://github.com/BuilderIO/qwik/assets/8991783/1fe16987-d981-4ad1-a4cc-a978f88f2719)

**Comment by PatrickJS** [comment]
should be fixed with https://github.com/BuilderIO/qwik/pull/6038
