### ISSUE TITLE
[🐞] Error Integrating React Libraries (Material ui) in Qwik Framework

### ISSUE THREAD

**Issue by samwalters3** [BuilderIO/qwik#6030]
### Which component is affected?

Qwik Runtime

### Describe the bug

I encountered an issue while attempting to integrate Material ui into a Qwik project, following the steps outlined in the [Qwik + React integration documentation](https://qwik.dev/docs/integrations/react/#6-using-react-libraries). Despite closely following the provided instructions, I encountered errors during the process.
---
React <Example/> Render
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at Example
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
12:14:02 PM [vite] Internal server error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
      at renderElement (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6047:9)
      at renderNodeDestructiveImpl (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
      at renderNodeDestructive (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
      at renderElement (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5975:9)
      at renderNodeDestructiveImpl (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
      at renderNodeDestructive (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
      at renderIndeterminateComponent (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5789:7)
      at renderElement (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
      at renderNodeDestructiveImpl (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
      at renderNodeDestructive (/home/eagle/github.com/qwik-app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)

### Reproduction

https://github.com/samwalters3/qwik-app

### Steps to reproduce

1. Create a new Qwik project with `npm create qwik@latest`.
2. Navigate into the project directory with `cd qwik-app`.
3. Option 1: Add React support with `npm run qwik add react`.
4. Option 2: Install necessary React and MUI packages with `npm install @builder.io/qwik-react @types/react @types/react-dom react react-dom @mui/material @emotion/react @emotion/styled`.
5. write the same example of https://qwik.dev/docs/integrations/react/#6-using-react-libraries
6. Run the project to observe the error - npm start.

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
    Memory: 3.19 GB / 7.67 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.4.0 - /usr/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
  npmPackages:
    @builder.io/qwik: ^1.5.1 => 1.5.1
    @builder.io/qwik-city: ^1.5.1 => 1.5.1
    @builder.io/qwik-react: ^0.5.4 => 0.5.4
    undici: * => 6.9.0
    vite: ^5.1.4 => 5.1.6

  "dependencies": {
    "@builder.io/qwik-react": "^0.5.4",
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.0",
    "@mui/material": "^5.15.14",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "@types/react": "^18.2.67",
    "@types/react-dom": "^18.2.22"
}
```

### Additional Information

Thanks for great job!

**Comment by samwalters3** [comment]
i've figured out the issue which is with the mui package!

**Comment by samwalters3** [comment]
The issue is not with qwik framework
