### ISSUE TITLE
dev.ssr script failing in QwikCity starter

### ISSUE THREAD

**Issue by lucis** [BuilderIO/qwik#614]
### Qwik Version

0.0.25

### Operating System (or Browser)

MacOS 11.6

### Node Version (if applicable)

16.14.0

### Which component is affected?

Qwik City

### Expected Behaviour

Running `yarn dev.ssr` in a recently created QwikCity starter should work.

### Actual Behaviour

Fails with error: 

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/lucis/personal/repro-problem/node_modules/@builder.io/qwik-city/pages/jobs/index.js' imported from /Users/lucis/personal/repro-problem/node_modules/@builder.io/qwik-city/dist/index.cjs
```

## How to reproduce

1. Run `npm init qwik@latest`
2. Select _QwikCity_ as the starter used.
3. `cd` your project's folder and run `npm install`
4. Run `npm run dev.ssr`

![image](https://user-images.githubusercontent.com/18706156/173257394-5873fa0f-d266-4126-a244-359503a75fdb.png)
![image](https://user-images.githubusercontent.com/18706156/173257421-32a1c1a4-abb6-480d-a01b-a7676a09e688.png)

**Comment by manucorporat** [comment]
Looking into it now!

**Comment by mahmoudajawad** [comment]
Another issue concerning QwikCity and SSR: #551

**Comment by atennert** [comment]
@wtho it doesn't solve the issue. I also tried using `npm run serve` after the full build, but this also tries to import the (generated?) pages from `node_modules/@builder.io/qwik-city`.

Here is the error output from `npm run serve`:

```
╭─[10:20]─[user]─[qwik-app]
╰─> npm run serve

> serve
> node server/entry.express.js

http://localhost:8080/
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/user/Projects/qwik-app/node_modules/@builder.io/qwik-city/pages/index.js' imported from /home/user/Projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ESMLoader.import (node:internal/modules/esm/loader:276:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1041:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
    at importModuleDynamically (node:vm:381:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
    at loadPage (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs:545:7)
    at Object.useQwikCity (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs:510:31)
    at /home/user/Projects/qwik-app/server/entry.express.js:129:12
    at useInvoke (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:221:30)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:351:32
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:341:24
    at renderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2532:35)
    at firstRenderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2509:16)
    at createElm (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2962:20)
    at addVnodes (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2830:27)
    at smartUpdateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2596:20)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2822:20
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at patchVnode (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2820:16)
    at updateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2629:30)
    at smartUpdateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2593:20)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2822:20
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at patchVnode (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2820:16)
    at updateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2629:30)
    at smartUpdateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2593:20)
    at visitJsxNode (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2473:20)
    at render (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4451:15)
    at async Object.renderToString (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:9733:3)
    at async /home/user/Projects/qwik-app/server/entry.express.js:191:20 {
  code: 'ERR_MODULE_NOT_FOUND'
}
QWIK ERROR Error: Cannot find module '/inlinedQRL.js'
Require stack:
- /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/server.cjs
- /home/user/Projects/qwik-app/server/entry.express.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.importSymbol (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:479:23)
    at qrlImport (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3997:49)
    at QRL.resolve (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:333:20)
    at _useStyles (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4640:32)
    at Object.useScopedStylesQrl (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4614:9)
    at /home/user/Projects/qwik-app/server/entry.express.js:99:8
    at useInvoke (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:221:30)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:351:32
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:341:24
    at renderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2532:35)
    at firstRenderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2509:16)
    at createElm (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2962:20)
    at addVnodes (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2830:27)
    at smartUpdateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2596:20)
    at visitJsxNode (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2473:20)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2571:32
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2570:28
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2537:24
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at renderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2534:20)
    at firstRenderComponent (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2509:16)
    at createElm (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2962:20)
    at addVnodes (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2830:27)
    at smartUpdateChildren (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2596:20)
    at visitJsxNode (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2470:20)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2571:32
    at then (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:293:70)
    at /home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2570:28
    at async Promise.all (index 0)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async render (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4451:9)
    at async Object.renderToString (/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:9733:3)
    at async /home/user/Projects/qwik-app/server/entry.express.js:191:20 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Projects/qwik-app/node_modules/@builder.io/qwik/server.cjs',
    '/home/user/Projects/qwik-app/server/entry.express.js'
  ]
}
```

**Comment by nnelgxorz** [comment]
Hey @lucis and @atennert! Qwik City now runs on Vite 3. My dev.ssr error is fixed now, wondering if your errors are also fixed if you create a new starter with `npm init qwik@latest`?

**Comment by atennert** [comment]
Thank you, it's working for me now :rocket:
