### ISSUE TITLE
$0.qwik.pause() fails serialization

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#702]
### Qwik Version

0.0.30

### Operating System (or Browser)

chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Serialize without an error

### Actual Behaviour

https://www.loom.com/share/9244d9eb2914440fb399ef97f1f3752b

### Additional Information

1. clone https://github.com/mhevery/qwik-conference
2. `yarn`
3. `yarn dev.ssr`
4. http://localhost:3000/todo

```
client.ts:16 [vite] connecting...
client.ts:53 [vite] connected.
$0.qwik.pause()
log.js:8 QWIK ERROR Error: Expected defined value
    at logError (log.js:6:54)
    at logErrorAndStop (log.js:12:5)
    at assertDefined (assert.js:8:15)
    at mustGetObjId (store.js:204:9)
    at store.js:282:37
    at Array.map (<anonymous>)
    at store.js:282:37
    at Array.forEach (<anonymous>)
    at snapshotState (store.js:268:11)
    at pauseContainer (store.js:33:11)
    at Object.pause (props.js:27:17)
    at <anonymous>:1:9
logError @ log.js:8
logErrorAndStop @ log.js:12
assertDefined @ assert.js:8
mustGetObjId @ store.js:204
(anonymous) @ store.js:282
(anonymous) @ store.js:282
snapshotState @ store.js:268
pauseContainer @ store.js:33
pause @ props.js:27
(anonymous) @ VM390:1
```

**Comment by manucorporat** [comment]
Fixed by https://github.com/BuilderIO/qwik/commit/170f6ba11792921d48e81ec9a793efe990e723a5
