### ISSUE TITLE
[Bug] Default Qwik City starter is broken.

### ISSUE THREAD

**Issue by isaac-mcfadyen** [BuilderIO/qwik#734]
### Qwik Version

v0.0.34

### Operating System (or Browser)

macOS Ventura 13.0

### Node Version (if applicable)

v18.2.0

### Which component is affected?

Qwik City v0.0.13

### Expected Behaviour

The default Qwik City starter launches properly (no errors) when using Cloudflare Pages.

### Actual Behaviour

Works fine when in dev mode (with Vite) but errors when the built version is run via `wrangler pages dev` or on Pages.

Callstack:
```
QWIK ERROR Error: Expected '' === 'html'.
    at logError$1 (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:1768:52)
    at logErrorAndStop$1 (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:1773:3)
    at assertEqual (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:1807:11)
    at smartUpdateChildren (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:3158:7)
    at visitJsxNode (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:3055:12)
    at render$1 (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:4662:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at renderToString (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:24460:3)
    at onRequestGet2 (/Users/isaac/Projects/qwik/server/entry.cloudflare.js:25578:20)
    at next (/Users/isaac/.config/yarn/global/node_modules/wrangler/templates/pages-template-worker.ts:129:22)
    at ServiceWorkerGlobalScope.[kDispatchFetch] (/Users/isaac/.config/yarn/global/node_modules/@miniflare/core/src/standards/event.ts:359:13)
    at Server.<anonymous> (/Users/isaac/.config/yarn/global/node_modules/@miniflare/http-server/src/index.ts:290:20)
```

Seems to be an error inside `smartUpdateChildren`, specifically the line `assertEqual(ch[0].$type$, "html");` which is failing because `ch[0].$type$` is empty.

### Additional Information

Default starter selected (with Cloudflare Pages). Nothing modified or changed.

**Comment by mhevery** [comment]
This should be resolved with the next Qwik City drop, which is in the works....
