### ISSUE TITLE
[Bug] Default Qwik City Express starter is broken. 

### ISSUE THREAD

**Issue by tjmgregory** [BuilderIO/qwik#744]
### Qwik Version

v0.0.34

### Operating System (or Browser)

MacOS 12.4

### Node Version (if applicable)

v16.13.1

### Which component is affected?

Qwik City v0.0.13

### Expected Behaviour

1. `npm init qwik@latest`
2. Choose Express and add Prettier and TailwindCSS
3. `cd qwik-city`
4. `npm install`
5. `npm run build`
6. `npm run serve`
7. Visit localhost:8080 and see Qwik City.

### Actual Behaviour

...
7. Visit localhost:8080, nothing loads
8. Two errors present in console:

    Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik-city/pages/index.js' imported from /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs
        at new NodeError (node:internal/errors:371:5)
        at finalizeResolution (node:internal/modules/esm/resolve:416:11)
        at moduleResolve (node:internal/modules/esm/resolve:932:10)
        at defaultResolve (node:internal/modules/esm/resolve:1044:11)
        at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
        at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
        at ESMLoader.import (node:internal/modules/esm/loader:276:22)
        at importModuleDynamically (node:internal/modules/cjs/loader:1041:29)
        at importModuleDynamicallyWrapper (node:internal/vm/module:437:21)
        at importModuleDynamically (node:vm:381:46)
        at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
        at loadPage (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs:545:7)
        at Object.useQwikCity (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik-city/dist/index.cjs:510:31)
        at /Users/theo/projects/qwik-app/server/entry.express.js:121:12
        at useInvoke (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:248:30)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3935:32
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3925:24
        at renderComponent (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2426:35)
        at createElm (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2864:20)
        at addVnodes (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2731:27)
        at smartUpdateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2501:20)
        at patchVnode (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2724:16)
        at updateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2534:30)
        at smartUpdateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2498:20)
        at patchVnode (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2724:16)
        at updateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2534:30)
        at smartUpdateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2498:20)
        at visitJsxNode (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2371:20)
        at render (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4443:15)
        at async Object.renderToString (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:9818:3)
        at async /Users/theo/projects/qwik-app/server/entry.express.js:198:20 {
      code: 'ERR_MODULE_NOT_FOUND'
    }
    QWIK ERROR Error: Cannot find module '/inlinedQRL.js'
    Require stack:
    - /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/server.cjs
    - /Users/theo/projects/qwik-app/server/entry.express.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.Module._resolveFilename (/Users/theo/projects/qwik-app/server/entry.express.js:185:12)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.importSymbol (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:567:23)
        at qrlImport (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3998:49)
        at QRL.resolve (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3917:20)
        at _useStyles (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4663:40)
        at Object.useScopedStylesQrl (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4637:9)
        at /Users/theo/projects/qwik-app/server/entry.express.js:91:8
        at useInvoke (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:248:30)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3935:32
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:3925:24
        at renderComponent (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2426:35)
        at createElm (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2864:20)
        at addVnodes (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2731:27)
        at smartUpdateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2501:20)
        at visitJsxNode (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2371:20)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2465:32
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2464:28
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2431:24
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at renderComponent (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2428:20)
        at createElm (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2864:20)
        at addVnodes (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2731:27)
        at smartUpdateChildren (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2501:20)
        at visitJsxNode (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2368:20)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2465:32
        at then (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:312:70)
        at /Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:2464:28
        at async Promise.all (index 0)
        at async Promise.all (index 1)
        at async Promise.all (index 0)
        at async render (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/core.cjs:4443:9)
        at async Object.renderToString (/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/server.cjs:9818:3)
        at async /Users/theo/projects/qwik-app/server/entry.express.js:198:20 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/Users/theo/projects/qwik-app/node_modules/@builder.io/qwik/server.cjs',
        '/Users/theo/projects/qwik-app/server/entry.express.js'
      ]
    }

### Additional Information

Have not done anything else to get setup. `dist` folder looks like it's populated with many appropriate files, but am new to Qwik so can't say for certain.

`npm run dev` works fine.

Seems different to this recent issue: https://github.com/BuilderIO/qwik/issues/734

**Comment by mhevery** [comment]
This should be resolved with the next Qwik City drop, which is in the works....
