### ISSUE TITLE
`build.full` fails on windows

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#794]
### Qwik Version

0.0.36

### Operating System (or Browser)

Windows 

### Node Version (if applicable)

16.13.0

### Which component is affected?

Qwik Optimizer (rust)

### Expected Behaviour

I expect to build all the projects successfully on my local windows machine

### Actual Behaviour

Reproduce:

1. Run `yarn build.full`

2. I see this error:

```
Internal Error: Command failed: cargo metadata --format-version 1
'cargo' is not recognized as an internal or external command,
operable program or batch file.
```

The full error:

```cmd

🦊 core.mjs: { original: '164.2kb', brotli: '29.8kb' }
🐭 core.min.mjs: { original: '32.2kb', brotli: '11.7kb' }
🐰 server
🐹 optimizer
▲ [WARNING] "espree" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/eslint/lib/rule-tester/rule-tester.js:55:35:
      55 │ const espreePath = require.resolve("espree");
         ╵                                    ~~~~~~~~

📐 eslint-plugin-qwik
Internal Error: Command failed: cargo metadata --format-version 1
'cargo' is not recognized as an internal or external command,
operable program or batch file.

'cargo' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at BuildCommand.<anonymous> (C:\dev\workspace\open-source\qwik\node_modules\@napi-rs\cli\scripts\index.js:14505:59)
    at Generator.next (<anonymous>)
    at fulfilled (C:\dev\workspace\open-source\qwik\node_modules\@napi-rs\cli\scripts\index.js:3423:58)

❌ napi exited with code 1
 c:\dev\workspace\open-source\qwik\scripts\util.ts:296
  console.error(`\n❌ ${msg}\n`, new Error(msg).stack);
                                 ^

Error: napi exited with code 1
    at null.panic (c:\dev\workspace\open-source\qwik\scripts\util.ts:296:33)
    at null.build (c:\dev\workspace\open-source\qwik\scripts\build.ts:129:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
```

**Comment by manucorporat** [comment]
Do you have rust installed in your computer?

**Comment by manucorporat** [comment]
We should probably update this doc: https://github.com/BuilderIO/qwik/blob/main/CONTRIBUTING.md

with all the details... will look into it, but i will need help to check it windows

**Comment by shairez** [comment]
@manucorporat I don't have rust

I can create a dockerfile that runs everything if you'd want, just write to me what it takes

**Comment by manucorporat** [comment]
We already have one for the devcontainer: https://github.com/BuilderIO/qwik/blob/main/.devcontainer/Dockerfile
