### ISSUE TITLE
npm run build: Error: spawn wasm-pack ENOENT

### ISSUE THREAD

**Issue by btakita** [BuilderIO/qwik#95]
```
❯ npm run build

> @builder.io/qwik@0.0.14 build
> node scripts --tsc --build --api --platform-binding --wasm

🌎 Qwik v0.0.14.20211202063605
🐶 tsc
🐷 generated package.json
🐮 jsx-runtime
🦁 testing
🐹 optimizer
🐸 qwikloader: 970b (590b gz)
🦊 core.mjs: 88.8kb (22.2kb gz)
🐨 prefetch: 975b (599b gz)
🐭 core.min.mjs: 22kb (8.1kb gz)
🐰 server
error: failed to parse manifest at `/home/brian/work/BuilderIO/qwik/src/napi/Cargo.toml`

Caused by:
  feature `edition2021` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["edition2021"]` to enable this feature
Internal Error: Command failed: cargo build --release
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at BuildCommand.<anonymous> (/home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:23590:42)
    at Generator.next (<anonymous>)
    at /home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:68:61
    at new Promise (<anonymous>)
    at __async (/home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:52:10)
    at BuildCommand.execute (/home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:23572:12)
    at BuildCommand.validateAndExecute (/home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:962:37)
    at Cli2.run (/home/brian/work/BuilderIO/qwik/node_modules/@napi-rs/cli/scripts/index.js:1992:36)

❌ napi exited with code 1
 Error: napi exited with code 1
    at panic (/home/brian/work/BuilderIO/qwik/scripts/util.ts:245:33)
    at build (/home/brian/work/BuilderIO/qwik/scripts/build.ts:109:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by btakita** [comment]
I needed run `rustup update`
